'use client'

import { createContext, useContext, useEffect, useMemo } from 'react'
import { usePathname, useRouter } from 'next/navigation'
import { isLocale, Locale, localizeHref } from '@/lib/i18n'

const arabic: Record<string, string> = {
  'HOME': 'الرئيسية',
  'ABOUT US': 'من نحن',
  'SERVICES': 'الخدمات',
  'CASE STUDIES': 'دراسات الحالة',
  'COURSES': 'الدورات',
  'CONTACT US': 'اتصل بنا',
  'WEB DEVELOPMENT': 'تطوير المواقع',
  'MOBILE APP DEVELOPMENT': 'تطوير تطبيقات الجوال',
  'DIGITAL MARKETING': 'التسويق الرقمي',
  'UI/UX DESIGN': 'تصميم واجهة وتجربة المستخدم',
  'VIDEO EDITING': 'تحرير الفيديو',
  'e-COMMERCE / Shopify': 'التجارة الإلكترونية / شوبيفاي',
  'Graphic Designing': 'التصميم الجرافيكي',
  'Video Graphy': 'التصوير بالفيديو',
  'Website Development': 'تطوير المواقع',
  'Social Media Marketing / Meta Ads': 'التسويق عبر التواصل / إعلانات ميتا',
  'Video Editing': 'تحرير الفيديو',
  'Graphic Design': 'التصميم الجرافيكي',
  'GRAPHIC DESIGN': 'التصميم الجرافيكي',
  'e-COMMERCE & Shopify': 'التجارة الإلكترونية وشوبيفاي',
  'GET A QUOTE': 'احصل على عرض سعر',
  'ENROLL NOW': 'سجّل الآن',
  'Follow Us': 'تابعنا',
  'Open menu': 'فتح القائمة',
  'Close menu': 'إغلاق القائمة',
  'Services': 'الخدمات',
  'Courses': 'الدورات',
  'Company': 'الشركة',
  'Support': 'الدعم',
  'Web Development': 'تطوير المواقع',
  'Digital Marketing': 'التسويق الرقمي',
  'Search Engine Optimization': 'تحسين محركات البحث',
  'E-Commerce': 'التجارة الإلكترونية',
  'e-Commerce & Shopify': 'التجارة الإلكترونية وشوبيفاي',
  'Home': 'الرئيسية',
  'About Us': 'من نحن',
  'Case Studies': 'دراسات الحالة',
  'Contact Us': 'اتصل بنا',
  'Payments': 'المدفوعات',
  'Name': 'الاسم', 'Business Name': 'اسم النشاط التجاري', 'Phone': 'الهاتف', 'Email Address': 'البريد الإلكتروني',
  'Select Services': 'اختر الخدمة', '(optional)': '(اختياري)', 'SEO Optimization': 'تحسين محركات البحث',
  'Card Holder': 'حامل البطاقة',
  'Email address is required.': 'البريد الإلكتروني مطلوب.', 'Please enter a valid amount.': 'يرجى إدخال مبلغ صحيح.',
  'Could not start payment': 'تعذر بدء عملية الدفع', 'Please wait…': 'يرجى الانتظار…', 'Send': 'إرسال',
  'Payment details': 'تفاصيل الدفع', 'Payment Successful': 'تم الدفع بنجاح',
  "Thank you! We'll be in touch shortly.": 'شكراً لك! سنتواصل معك قريباً.',
  'Payment failed. Please try again.': 'فشلت عملية الدفع. يرجى المحاولة مرة أخرى.',
  'Total Amount:': 'المبلغ الإجمالي:', 'Processing…': 'جارٍ المعالجة…', 'Pay': 'ادفع', 'Amount in AED': 'المبلغ بالدرهم الإماراتي',
  'Decasoft specializes in custom design and front-end development. We love taking on design challenges that require full-on content strategy, thoughtful design, and ongoing marketing.': 'تتخصص ديكاسوفت في التصميم المخصص وتطوير الواجهات الأمامية. نواجه تحديات التصميم من خلال استراتيجية محتوى متكاملة وتصميم مدروس وتسويق مستمر.',
  'All Rights Reserved by Decasofts': 'جميع الحقوق محفوظة لشركة ديكاسوفت',
  'RESULTS DRIVEN DIGITAL MARKETING AGENCY': 'وكالة تسويق رقمي تركّز على النتائج',
  'We Drive Traffic.': 'نزيد زياراتك.',
  'You Get': 'وتحقق أنت',
  'Real Growth.': 'نمواً حقيقياً.',
  'Performance marketing solutions that help your business rank higher, get more leads and increase revenue.': 'حلول تسويق قائمة على الأداء تساعد مشروعك على تصدر النتائج وجذب المزيد من العملاء وزيادة الإيرادات.',
  'GET A FREE STRATEGY CALL': 'احجز مكالمة استراتيجية مجانية',
  'VIEW CASE STUDIES': 'شاهد دراسات الحالة',
  '600+ Happy Clients': 'أكثر من 600 عميل سعيد',
  '4.9 (200+ Reviews)': '4.9 (أكثر من 200 تقييم)',
  'Who We Are': 'من نحن',
  'About': 'عن',
  'We are a customer-focused digital agency helping ambitious businesses turn ideas into effective online experiences. From strategy and design to development and marketing, our team combines creativity with practical technology to produce measurable results.': 'نحن وكالة رقمية تركز على العملاء، ونساعد الشركات الطموحة على تحويل أفكارها إلى تجارب رقمية فعالة. من الاستراتيجية والتصميم إلى التطوير والتسويق، يجمع فريقنا بين الإبداع والتقنية لتحقيق نتائج قابلة للقياس.',
  'Purpose-built ideas': 'أفكار مصممة لهدفك',
  'Digital solutions shaped around your goals, audience, and market.': 'حلول رقمية مصممة حول أهدافك وجمهورك وسوقك.',
  'A team that listens': 'فريق يستمع إليك',
  'Clear communication and close collaboration from brief to launch.': 'تواصل واضح وتعاون وثيق من الفكرة حتى الإطلاق.',
  'Quality that lasts': 'جودة تدوم',
  'Reliable work delivered with care, consistency, and attention to detail.': 'عمل موثوق يُنفذ بعناية واتساق واهتمام بالتفاصيل.',
  '7+ Years': 'أكثر من 7 سنوات',
  'Creating digital impact': 'نصنع أثراً رقمياً',
  'Discover our story': 'اكتشف قصتنا',
  'Ready to Grow Your Business?': 'هل أنت مستعد لتنمية أعمالك؟',
  "Book your FREE strategy call today and let's build a growth engine for your brand.": 'احجز مكالمتك الاستراتيجية المجانية اليوم ولنصنع محرك نمو لعلامتك التجارية.',
  'GET A FREE PROPOSAL': 'احصل على عرض مجاني',
  'OUR SERVICES': 'خدماتنا', 'Smart Solutions.': 'حلول ذكية.', 'Real Results.': 'نتائج حقيقية.',
  'We offer a complete range of digital marketing services to help your business grow and dominate online.': 'نقدم خدمات رقمية متكاملة لمساعدة أعمالك على النمو وتعزيز حضورها عبر الإنترنت.',
  'Fast, responsive and SEO-friendly websites designed to convert visitors into customers.': 'مواقع سريعة ومتجاوبة ومهيأة لمحركات البحث لتحويل الزوار إلى عملاء.',
  'Grow your online presence with coordinated campaigns that attract, engage and convert.': 'نمِّ حضورك الرقمي بحملات متكاملة تجذب الجمهور وتحوله إلى عملاء.',
  'eCommerce Development': 'تطوير التجارة الإلكترونية', 'Launch a fast, secure online store designed to simplify shopping and increase sales.': 'أطلق متجراً سريعاً وآمناً يسهل التسوق ويزيد المبيعات.',
  'App Development': 'تطوير التطبيقات', 'Build reliable, user-friendly mobile apps tailored to your customers and business goals.': 'أنشئ تطبيقات جوال موثوقة وسهلة الاستخدام تناسب أهداف أعمالك.',
  'Stand out with memorable logos, brand identities and visuals created for every platform.': 'تميّز بشعارات وهويات بصرية وتصاميم جذابة لكل منصة.',
  'Google Ads': 'إعلانات جوجل', 'Drive high-quality traffic and maximize returns with smart Google Ads campaigns.': 'اجذب زيارات عالية الجودة وعظّم العائد بحملات إعلانات جوجل الذكية.',
  'Videography': 'التصوير بالفيديو', 'Tell your story with professional video production that captures attention and builds trust.': 'اروِ قصتك بإنتاج فيديو احترافي يجذب الانتباه ويبني الثقة.',
  'Email Marketing': 'التسويق عبر البريد الإلكتروني', 'Nurture leads and increase sales with high-converting email marketing campaigns.': 'نمِّ العملاء المحتملين وزد المبيعات بحملات بريد إلكتروني فعالة.',
  'View All Services': 'عرض جميع الخدمات',
  'OUR PROCESS': 'آلية عملنا', 'How We': 'كيف', 'Drive Your Success': 'نقود نجاحك',
  'Discover': 'الاكتشاف', 'We analyze your business, audience and competitors.': 'نحلل أعمالك وجمهورك ومنافسيك.',
  'Strategy': 'الاستراتيجية', 'We create a custom strategy based on data and insights.': 'نضع استراتيجية مخصصة مبنية على البيانات والرؤى.',
  'Campaign Launch': 'إطلاق الحملة', 'We launch high-performing campaigns that convert.': 'نطلق حملات عالية الأداء تحقق التحويلات.',
  'Optimize': 'التحسين', 'We continuously test and optimize for better results.': 'نختبر ونحسن باستمرار للوصول إلى نتائج أفضل.',
  'Scale': 'التوسع', 'We scale what works and maximize your ROI.': 'نوسع ما ينجح ونعظم عائد استثمارك.',
  'Step 01': 'الخطوة 01', 'Step 02': 'الخطوة 02', 'Step 03': 'الخطوة 03', 'Step 04': 'الخطوة 04', 'Step 05': 'الخطوة 05',
  'Projects Delivered': 'مشروعاً منجزاً', 'Happy Clients': 'عميلاً سعيداً', 'Ad Spend Managed': 'إنفاق إعلاني مُدار', 'Average ROAS': 'متوسط العائد الإعلاني', 'Years Experience': 'سنوات من الخبرة',
  'Start a project': 'ابدأ مشروعاً', 'View our work': 'شاهد أعمالنا', 'What we do': 'ما نقدمه', 'Our process': 'آلية عملنا',
  'Strategy-led approach': 'نهج تقوده الاستراتيجية', 'Clear collaboration': 'تعاون واضح', 'Quality-assured delivery': 'تنفيذ مضمون الجودة',
  'Plan': 'التخطيط', 'Create': 'التنفيذ', 'Deliver': 'التسليم',
  'We align on your goals, audience, competition, and priority outcomes.': 'نتفق على أهدافك وجمهورك ومنافسيك والنتائج ذات الأولوية.',
  'We translate insight into a focused roadmap, deliverables, and milestones.': 'نحوّل الرؤى إلى خارطة طريق ومخرجات ومراحل واضحة.',
  'Our specialists build, review, and refine with quality checks at every stage.': 'ينفذ خبراؤنا العمل ويراجعونه ويحسنونه مع فحص الجودة في كل مرحلة.',
  'You receive a polished solution, clear handover, and ongoing support.': 'تحصل على حل متكامل وتسليم واضح ودعم مستمر.',
  'Web Development Services': 'خدمات تطوير المواقع', 'Websites engineered to': 'مواقع مصممة من أجل', 'turn attention into growth.': 'تحويل الاهتمام إلى نمو.',
  'We design and develop fast, responsive, conversion-focused websites that give your business a stronger digital foundation and a better customer experience.': 'نصمم ونطور مواقع سريعة ومتجاوبة تركز على التحويل، لتمنح أعمالك أساساً رقمياً أقوى وتجربة أفضل للعملاء.',
  'Modern web solutions built around your business.': 'حلول ويب حديثة مصممة حول أعمالك.',
  'Digital Marketing Services': 'خدمات التسويق الرقمي', 'Campaigns that reach people and': 'حملات تصل إلى الناس', 'move them to act.': 'وتدفعهم إلى التفاعل.',
  'We connect strategy, content, media, and measurement to build awareness, generate qualified leads, and improve return on spend.': 'نربط الاستراتيجية والمحتوى والإعلام والقياس لبناء الوعي وجذب العملاء وتحسين العائد.',
  'Full-funnel marketing with measurable direction.': 'تسويق متكامل بنتائج قابلة للقياس.',
  'Mobile App Development': 'تطوير تطبيقات الجوال', 'Mobile products designed to': 'منتجات جوال مصممة لكي', 'earn a place on every screen.': 'تستحق مكاناً على كل شاشة.',
  'We design and develop reliable iOS and Android applications that feel intuitive, perform smoothly, and give your business a scalable mobile foundation.': 'نصمم ونطور تطبيقات iOS وأندرويد موثوقة وسهلة الاستخدام وعالية الأداء وقابلة للتوسع.',
  'UI/UX Design Services': 'خدمات تصميم واجهة وتجربة المستخدم', 'Digital experiences people': 'تجارب رقمية يفهمها الناس', 'understand and enjoy.': 'ويستمتعون بها.',
  'We combine user research, product thinking, and visual design to create interfaces that feel intuitive, reduce friction, and guide users toward action.': 'نجمع بين بحث المستخدم والتفكير في المنتج والتصميم البصري لإنشاء واجهات سهلة تقلل التعقيد وتوجه المستخدم إلى الإجراء.',
  'E-commerce & Shopify Services': 'خدمات التجارة الإلكترونية وشوبيفاي', 'Online stores designed to': 'متاجر إلكترونية مصممة لكي', 'sell more with less friction.': 'تبيع أكثر وبخطوات أسهل.',
  'We create high-performing Shopify and custom commerce experiences that make products easier to discover, compare, purchase, and return to.': 'ننشيء متاجر شوبيفاي وتجارب تجارة مخصصة عالية الأداء تسهل اكتشاف المنتجات ومقارنتها وشراءها.',
  'Graphic Designing Services': 'خدمات التصميم الجرافيكي', 'Design that makes your brand': 'تصميم يجعل علامتك', 'impossible to ignore.': 'لا يمكن تجاهلها.',
  'Video Editing Services': 'خدمات تحرير الفيديو', 'Raw footage transformed into': 'نحوّل اللقطات الخام إلى', 'stories people remember.': 'قصص يتذكرها الناس.',
  'Videography Services': 'خدمات التصوير بالفيديو', 'Visual stories captured with': 'قصص بصرية نلتقطها', 'purpose and cinematic craft.': 'بهدف وحرفية سينمائية.',
  'Selected work': 'أعمال مختارة', 'Explore case studies': 'استكشف دراسات الحالة', "Let's build what's next": 'لنبنِ الخطوة القادمة',
  'Clear scope': 'نطاق واضح', 'Dedicated team': 'فريق متخصص', 'Reliable communication': 'تواصل موثوق', 'Get a free consultation': 'احصل على استشارة مجانية',
  'About Decasoft': 'عن ديكاسوفت',
  'We bring strategy, creativity, and technology': 'نجمع الاستراتيجية والإبداع والتكنولوجيا',
  'into one team.': 'في فريق واحد.',
  'Decasoft is a digital agency helping organizations build stronger brands, better customer experiences, and scalable digital products across Pakistan and the UAE.': 'ديكاسوفت وكالة رقمية تساعد المؤسسات على بناء علامات تجارية أقوى وتجارب عملاء أفضل ومنتجات رقمية قابلة للتوسع في باكستان والإمارات.',
  'Work with us': 'اعمل معنا', 'Explore our services': 'استكشف خدماتنا',
  'Customer focused': 'نركز على العميل', 'Quality driven': 'الجودة تقودنا', 'Built for long-term growth': 'مصمم للنمو طويل الأمد',
  'Projects': 'مشروع', 'Clients': 'عميل', 'Years': 'سنوات',
  'Our story': 'قصتنا', 'Built to make digital work feel more connected.': 'بُنيت لجعل العمل الرقمي أكثر ترابطاً.',
  'Decasoft began with a straightforward belief: businesses should not have to coordinate disconnected vendors to create one consistent customer experience. We built a multidisciplinary team where designers, developers, marketers, and content specialists solve problems together.': 'بدأت ديكاسوفت بقناعة بسيطة: لا ينبغي للشركات تنسيق موردين منفصلين لصنع تجربة عميل متسقة. لذلك بنينا فريقاً متعدد التخصصات يجمع المصممين والمطورين والمسوقين ومتخصصي المحتوى لحل المشكلات معاً.',
  'Today, we partner with growing companies and established organizations to move from an early idea to a polished launch—and continue improving long after delivery.': 'اليوم نتعاون مع الشركات النامية والمؤسسات الراسخة للانتقال من الفكرة الأولى إلى إطلاق متقن، ونواصل التحسين بعد التسليم.',
  'One connected delivery team': 'فريق تنفيذ متكامل', 'Clear scopes and milestones': 'نطاق ومراحل واضحة', 'Senior specialist oversight': 'إشراف خبراء متمرسين', 'Support beyond launch': 'دعم مستمر بعد الإطلاق',
  'What guides us': 'ما يوجّهنا', 'Principles that shape every partnership.': 'مبادئ تشكّل كل شراكة.',
  'Our values are practical standards for how we make decisions, communicate, and deliver.': 'قيمنا معايير عملية لطريقة اتخاذ القرارات والتواصل والتنفيذ.',
  'Outcome focused': 'التركيز على النتائج', 'We connect every creative and technical decision to a clear business objective.': 'نربط كل قرار إبداعي وتقني بهدف تجاري واضح.',
  'True collaboration': 'تعاون حقيقي', 'We work openly with clients, share context early, and solve challenges as one team.': 'نعمل بشفافية مع العملاء ونشارك السياق مبكراً ونحل التحديات كفريق واحد.',
  'Thoughtful innovation': 'ابتكار مدروس', 'We use new ideas and technology where they create real value—not simply because they are new.': 'نستخدم الأفكار والتقنيات الجديدة عندما تصنع قيمة حقيقية، لا لمجرد أنها جديدة.',
  'Quality with accountability': 'جودة بمسؤولية', 'Clear ownership, careful reviews, and dependable delivery are built into how we work.': 'المسؤولية الواضحة والمراجعة الدقيقة والتنفيذ الموثوق جزء أساسي من عملنا.',
  'What we build': 'ما نبنيه', 'Solutions Decasoft Offers': 'حلول تقدمها ديكاسوفت',
  'Flexible digital products and business systems shaped around your operations, customers, and growth plans.': 'منتجات رقمية وأنظمة أعمال مرنة مصممة وفق عملياتك وعملائك وخطط نموك.',
  'Enterprise Applications': 'تطبيقات المؤسسات', 'ERP Systems': 'أنظمة تخطيط موارد المؤسسات', 'CRM Solutions': 'حلول إدارة علاقات العملاء', 'Salon Management': 'إدارة الصالونات',
  'Inventory Management': 'إدارة المخزون', 'Asset Management': 'إدارة الأصول', 'Marketplace Software': 'برمجيات الأسواق الإلكترونية', 'MVP Development': 'تطوير المنتج الأولي',
  'Web Portals': 'بوابات الويب', 'Payment Software': 'برمجيات الدفع', 'Finance Software': 'البرمجيات المالية', 'Event Management': 'إدارة الفعاليات',
  'Healthcare Solutions': 'حلول الرعاية الصحية', 'HR Management Systems': 'أنظمة إدارة الموارد البشرية', 'E-commerce Development': 'تطوير التجارة الإلكترونية', 'Construction Software': 'برمجيات الإنشاءات',
  'Across industries': 'عبر مختلف القطاعات', 'Industries We Cover': 'القطاعات التي نخدمها',
  'We combine proven digital practices with a practical understanding of the customers, constraints, and opportunities in each sector.': 'نجمع الممارسات الرقمية المثبتة مع فهم عملي للعملاء والتحديات والفرص في كل قطاع.',
  'Serving clients across Pakistan and the UAE': 'نخدم العملاء في باكستان والإمارات',
  'Healthcare': 'الرعاية الصحية', 'Manufacturing': 'التصنيع', 'Retail': 'التجزئة', 'Education': 'التعليم', 'Logistics': 'الخدمات اللوجستية', 'Startups': 'الشركات الناشئة', 'Marketing': 'التسويق', 'Blockchain': 'سلاسل الكتل', 'Property': 'العقارات', 'School': 'المدارس',
  'How we partner': 'كيف نتعاون', 'Close enough to understand. Experienced enough to challenge.': 'قريبون بما يكفي لنفهم، وخبراء بما يكفي لنتحدى.',
  '“Our role is not simply to complete a list of tasks. It is to understand what success looks like, bring the right specialists together, and help our clients make stronger digital decisions.”': '«دورنا ليس مجرد إكمال قائمة مهام، بل فهم معنى النجاح وجمع المتخصصين المناسبين ومساعدة عملائنا على اتخاذ قرارات رقمية أقوى.»',
  'The Decasoft approach': 'نهج ديكاسوفت', 'Customer focused. Quality driven.': 'نركز على العميل. وتقودنا الجودة.',
  "Let's work together": 'لنعمل معاً', 'Looking for a digital partner who sees the bigger picture?': 'هل تبحث عن شريك رقمي يرى الصورة الأكبر؟', 'Start a conversation': 'ابدأ المحادثة',
  'Campaign design with clarity and impact': 'تصميم حملات بوضوح وتأثير', 'Everything your brand needs to show up with confidence.': 'كل ما تحتاجه علامتك التجارية للظهور بثقة.',
  'Brand Identity': 'هوية العلامة التجارية', 'Logos, color systems, typography, and guidelines built for recognition.': 'شعارات وأنظمة ألوان وخطوط وإرشادات مصممة لتعزيز التعرّف على علامتك.',
  'Social Media Design': 'تصميم وسائل التواصل الاجتماعي', 'Scroll-stopping posts, stories, and advertising creative for every platform.': 'منشورات وقصص وإعلانات جذابة مصممة لكل منصة.',
  'Packaging Design': 'تصميم العبوات', 'Shelf-ready packaging that communicates value and earns attention.': 'عبوات جاهزة للعرض توضح القيمة وتجذب الانتباه.',
  'Marketing Collateral': 'المواد التسويقية', 'Brochures, profiles, presentations, flyers, and polished print assets.': 'كتيبات وملفات تعريفية وعروض تقديمية ومنشورات ومواد مطبوعة متقنة.',
  'Illustration & Artwork': 'الرسوم والأعمال الفنية', 'Custom illustration, icons, and artwork with a distinctive personality.': 'رسوم وأيقونات وأعمال فنية مخصصة بطابع مميز.',
  'Digital Campaigns': 'الحملات الرقمية', 'Cohesive visual systems for launches, web, email, and advertising.': 'أنظمة بصرية متناسقة للإطلاقات والويب والبريد الإلكتروني والإعلانات.',
  'Good design starts before the first sketch.': 'يبدأ التصميم الجيد قبل أول رسم.', 'Designed to perform in the real world.': 'تصاميم تؤدي بفاعلية في العالم الحقيقي.', 'Ready for a visual identity that works as hard as you do?': 'هل أنت مستعد لهوية بصرية تعمل بجد مثلك؟',

  'Fast, scalable, conversion-ready websites': 'مواقع سريعة وقابلة للتوسع وجاهزة لتحقيق التحويلات',
  'Custom Development': 'تطوير مخصص', 'Purpose-built websites and applications aligned with your workflows.': 'مواقع وتطبيقات مصممة خصيصاً لتتوافق مع سير عملك.',
  'Responsive Experiences': 'تجارب متجاوبة', 'Thoughtful interfaces that perform beautifully on every screen.': 'واجهات مدروسة تعمل بكفاءة على كل شاشة.',
  'Reliable online stores with intuitive, secure buying journeys.': 'متاجر إلكترونية موثوقة توفر رحلة شراء سهلة وآمنة.',
  'Speed Optimization': 'تحسين السرعة', 'Performance engineering for faster loading and stronger usability.': 'هندسة أداء لتحميل أسرع وتجربة استخدام أفضل.',
  'CMS Solutions': 'حلول إدارة المحتوى', 'Flexible systems that make publishing and content management easy.': 'أنظمة مرنة تسهّل النشر وإدارة المحتوى.',
  'Support & Maintenance': 'الدعم والصيانة', 'Ongoing updates, monitoring, improvements, and technical support.': 'تحديثات ومراقبة وتحسينات ودعم تقني مستمر.',
  'A reliable website begins with the right technical plan.': 'يبدأ الموقع الموثوق بخطة تقنية صحيحة.', 'Digital experiences built to deliver results.': 'تجارب رقمية مصممة لتحقيق النتائج.', 'Ready to build a website that moves your business forward?': 'هل أنت مستعد لبناء موقع يدفع أعمالك إلى الأمام؟',

  'Native-quality experiences built around real users': 'تجارب بجودة أصلية مصممة حول المستخدمين الحقيقيين', 'From product idea to polished mobile experience.': 'من فكرة المنتج إلى تجربة جوال متقنة.',
  'iOS Development': 'تطوير تطبيقات iOS', 'Responsive, secure applications created for the Apple ecosystem.': 'تطبيقات آمنة ومتجاوبة مصممة لمنظومة آبل.',
  'Android Development': 'تطوير تطبيقات أندرويد', 'Reliable Android experiences optimized across devices and screen sizes.': 'تجارب أندرويد موثوقة ومحسّنة لمختلف الأجهزة وأحجام الشاشات.',
  'Cross-platform Apps': 'تطبيقات متعددة المنصات', 'Efficient React Native and Flutter builds with a consistent native feel.': 'تطبيقات فعالة باستخدام React Native وFlutter بتجربة أصلية متناسقة.',
  'Mobile UI/UX': 'تصميم واجهة وتجربة الجوال', 'Clear navigation and accessible interfaces designed for touch-first use.': 'تنقل واضح وواجهات سهلة الوصول مصممة للاستخدام باللمس.',
  'API & Integrations': 'واجهات البرمجة والتكاملات', 'Secure connections to payments, CRM, analytics, maps, and business systems.': 'اتصالات آمنة مع الدفع وإدارة العملاء والتحليلات والخرائط وأنظمة الأعمال.',
  'App Optimization': 'تحسين التطبيقات', 'Performance, stability, testing, store readiness, and ongoing improvements.': 'تحسين الأداء والاستقرار والاختبارات والجاهزية للمتاجر والتطوير المستمر.',
  'Successful apps begin with the right product decisions.': 'تبدأ التطبيقات الناجحة بقرارات المنتج الصحيحة.', 'Mobile experiences shaped for everyday use.': 'تجارب جوال مصممة للاستخدام اليومي.', 'Ready to turn your mobile app idea into a product people value?': 'هل أنت مستعد لتحويل فكرة تطبيقك إلى منتج يقدّره المستخدمون؟',

  'Strategy and creative working as one': 'الاستراتيجية والإبداع يعملان معاً',
  'Paid Advertising': 'الإعلانات المدفوعة', 'Focused Meta and Google campaigns for high-intent audiences.': 'حملات مركزة على ميتا وجوجل للجمهور الأكثر استعداداً للتفاعل.',
  'Social Media Marketing': 'التسويق عبر وسائل التواصل الاجتماعي', 'Content and community strategies that build attention and trust.': 'استراتيجيات محتوى ومجتمع تبني الاهتمام والثقة.',
  'Content Strategy': 'استراتيجية المحتوى', 'Useful, persuasive content aligned with the customer journey.': 'محتوى مفيد ومقنع يتوافق مع رحلة العميل.',
  'Analytics & Reporting': 'التحليلات والتقارير', 'Clear insights that turn performance into confident decisions.': 'رؤى واضحة تحول الأداء إلى قرارات واثقة.',
  'Conversion Optimization': 'تحسين التحويلات', 'Campaign and landing-page improvements that increase results.': 'تحسين الحملات وصفحات الهبوط لزيادة النتائج.',
  'Search Marketing': 'التسويق عبر البحث', 'Organic and paid programs that capture existing demand.': 'برامج بحث عضوية ومدفوعة تستفيد من الطلب القائم.',
  'Strong marketing is a system, not a collection of posts.': 'التسويق القوي منظومة متكاملة وليس مجموعة منشورات.', 'Creative campaigns grounded in performance.': 'حملات إبداعية مبنية على الأداء.', 'Ready to turn your marketing budget into measurable growth?': 'هل أنت مستعد لتحويل ميزانيتك التسويقية إلى نمو قابل للقياس؟',

  'Search strategy built for lasting visibility': 'استراتيجية بحث لبناء ظهور مستدام', 'A complete SEO program, not isolated tactics.': 'برنامج متكامل لتحسين محركات البحث، لا أساليب منفصلة.',
  'SEO Audits': 'تدقيق تحسين محركات البحث', 'Technical, content, authority, and competitor opportunity analysis.': 'تحليل تقني وللمحتوى والموثوقية وفرص المنافسين.',
  'Technical SEO': 'تحسين تقني لمحركات البحث', 'Structure, speed, crawling, indexing, schema, and Core Web Vitals.': 'تحسين البنية والسرعة والزحف والفهرسة والبيانات المنظمة ومؤشرات الويب.',
  'Content Optimization': 'تحسين المحتوى', 'Search-focused pages that answer genuine customer needs.': 'صفحات مهيأة للبحث تجيب عن احتياجات العملاء الحقيقية.',
  'Local SEO': 'تحسين البحث المحلي', 'Local visibility that connects nearby customers with your business.': 'ظهور محلي يصل العملاء القريبين بأعمالك.',
  'Authority Building': 'بناء الموثوقية', 'Ethical outreach and digital PR that strengthen credibility.': 'تواصل مسؤول وعلاقات عامة رقمية تعزز المصداقية.',
  'SEO Reporting': 'تقارير تحسين محركات البحث', 'Transparent rankings, traffic, conversion, and opportunity reporting.': 'تقارير شفافة للترتيب والزيارات والتحويلات والفرص.',
  'Lasting rankings begin with evidence and priorities.': 'تبدأ النتائج المستدامة بالأدلة والأولويات.', 'Websites positioned for discovery and growth.': 'مواقع مهيأة للاكتشاف والنمو.', 'Ready to earn visibility from the searches that matter?': 'هل أنت مستعد للظهور في عمليات البحث المهمة؟',

  'Clear interfaces shaped around real users': 'واجهات واضحة مصممة حول المستخدمين الحقيقيين', 'Thoughtful product design from insight to interface.': 'تصميم منتج مدروس من الفكرة إلى الواجهة.',
  'User Research': 'بحث المستخدمين', 'Personas, journeys, interviews, and evidence that reveal real needs.': 'شخصيات ورحلات ومقابلات وأدلة تكشف الاحتياجات الحقيقية.',
  'UX Architecture': 'هيكلة تجربة المستخدم', 'Clear flows, structures, and wireframes that simplify complex tasks.': 'مسارات وهياكل ونماذج أولية واضحة تبسّط المهام المعقدة.',
  'Interface Design': 'تصميم الواجهات', 'Polished, accessible interfaces aligned with your product and brand.': 'واجهات متقنة وسهلة الوصول ومتوافقة مع منتجك وعلامتك.',
  'Responsive Design': 'التصميم المتجاوب', 'Consistent experiences across mobile, tablet, and desktop.': 'تجارب متناسقة عبر الجوال والجهاز اللوحي وسطح المكتب.',
  'Design Systems': 'أنظمة التصميم', 'Reusable components that improve consistency and delivery speed.': 'مكونات قابلة لإعادة الاستخدام تحسن الاتساق وسرعة التنفيذ.',
  'Usability Testing': 'اختبار سهولة الاستخدام', 'Prototype validation before costly development decisions.': 'التحقق من النماذج الأولية قبل اتخاذ قرارات تطوير مكلفة.',
  'Great experiences are designed around evidence, not assumptions.': 'تُصمم التجارب الرائعة حول الأدلة لا الافتراضات.', 'Interfaces that balance beauty and usability.': 'واجهات توازن بين الجمال وسهولة الاستخدام.', 'Ready to make your digital product easier to love?': 'هل أنت مستعد لجعل منتجك الرقمي أسهل وأحب للمستخدمين؟',

  'Commerce experiences optimized for conversion': 'تجارب تجارة محسّنة لزيادة التحويل', 'Everything needed to launch and scale your store.': 'كل ما تحتاجه لإطلاق متجرك وتوسيعه.',
  'Shopify Development': 'تطوير شوبيفاي', 'Branded, flexible Shopify stores that are easy to manage.': 'متاجر شوبيفاي مرنة بهوية علامتك وسهلة الإدارة.',
  'Custom E-commerce': 'تجارة إلكترونية مخصصة', 'Tailored solutions for unique catalogs and workflows.': 'حلول مخصصة للكتالوجات ومسارات العمل الفريدة.',
  'Storefront UX': 'تجربة واجهة المتجر', 'Conversion-focused collection, product, cart, and checkout journeys.': 'رحلات تصفح وشراء ودفع مصممة لزيادة التحويل.',
  'System Integrations': 'تكامل الأنظمة', 'Payments, inventory, shipping, CRM, and marketplace connections.': 'تكاملات الدفع والمخزون والشحن وإدارة العملاء والأسواق.',
  'Performance': 'الأداء', 'Speed improvements that protect conversion and search visibility.': 'تحسينات سرعة تحافظ على التحويل والظهور في البحث.',
  'Growth Optimization': 'تحسين النمو', 'Data-led improvements to merchandising and retention.': 'تحسينات مبنية على البيانات للتسويق والاحتفاظ بالعملاء.',
  'Successful commerce connects customer needs with operations.': 'التجارة الناجحة تربط احتياجات العملاء بالعمليات.', 'Storefronts built for confident buying.': 'واجهات متاجر مصممة لشراء واثق.', 'Ready to build an online store customers return to?': 'هل أنت مستعد لبناء متجر إلكتروني يعود إليه العملاء؟',

  'Precision editing for every screen': 'مونتاج دقيق لكل شاشة', 'Post-production that gives every frame a purpose.': 'معالجة ما بعد الإنتاج تمنح كل إطار هدفاً.',
  'Professional Editing': 'مونتاج احترافي', 'Narrative structure, pacing, transitions, and final polish.': 'بناء سردي وإيقاع وانتقالات ولمسات نهائية متقنة.',
  'Motion Graphics': 'الرسوم المتحركة', 'Titles, explainers, lower thirds, and animated elements.': 'عناوين وشروحات وعناصر تعريفية ورسوم متحركة.',
  'Color Grading': 'تدرج الألوان', 'Consistent cinematic color that establishes mood.': 'ألوان سينمائية متناسقة تصنع الأجواء المطلوبة.',
  'Sound Design': 'تصميم الصوت', 'Clean dialogue, balanced audio, music, and effects.': 'حوار نقي وصوت متوازن وموسيقى ومؤثرات.',
  'Social Video': 'فيديو التواصل الاجتماعي', 'Platform-native reels, ads, shorts, and captions.': 'مقاطع قصيرة وإعلانات وترجمات ملائمة لكل منصة.',
  'Content Repurposing': 'إعادة توظيف المحتوى', 'Focused cutdowns and variations that extend every shoot.': 'نسخ مختصرة ومتنوعة تزيد الاستفادة من كل تصوير.',
  'A strong edit is where footage becomes communication.': 'في المونتاج القوي تتحول اللقطات إلى رسالة.', 'Every cut designed to keep attention.': 'كل لقطة مصممة للحفاظ على الانتباه.', 'Ready to turn your footage into content that connects?': 'هل أنت مستعد لتحويل لقطاتك إلى محتوى مؤثر؟',

  'Production built around your story': 'إنتاج مصمم حول قصتك', 'Complete video production for brands and campaigns.': 'إنتاج فيديو متكامل للعلامات التجارية والحملات.',
  'Brand Films': 'أفلام العلامة التجارية', 'Story-led films that communicate who you are and why it matters.': 'أفلام تقودها القصة وتوضح هويتك وأهميتك.',
  'Corporate Video': 'فيديو الشركات', 'Interviews, profiles, training, and company communications.': 'مقابلات وملفات تعريفية وتدريب واتصالات الشركات.',
  'Commercial Content': 'المحتوى التجاري', 'Product and campaign films for paid and organic channels.': 'أفلام للمنتجات والحملات عبر القنوات المدفوعة والعضوية.',
  'Event Coverage': 'تغطية الفعاليات', 'Key moments and atmosphere captured with a polished style.': 'التقاط اللحظات المهمة وأجواء الحدث بأسلوب متقن.',
  'Creative Direction': 'الإخراج الإبداعي', 'Concepts, scripts, storyboards, planning, and on-set direction.': 'أفكار ونصوص ولوحات قصصية وتخطيط وإخراج أثناء التصوير.',
  'Post-production': 'ما بعد الإنتاج', 'Editing, color, sound, graphics, captions, and final formats.': 'مونتاج وألوان وصوت ورسوم وترجمات وصيغ نهائية.',
  'The best shoots are won in planning and elevated in post.': 'ينجح أفضل تصوير بالتخطيط ويرتقي في مرحلة ما بعد الإنتاج.', 'Stories framed to create a lasting impression.': 'قصص مصوّرة لتترك انطباعاً دائماً.', 'Ready to bring your next story to the screen?': 'هل أنت مستعد لإظهار قصتك التالية على الشاشة؟',
  'We turn strategy into memorable visual identities, campaign creatives, and marketing assets that help ambitious brands look credible, consistent, and ready to grow.': 'نحوّل الاستراتيجية إلى هويات بصرية راسخة وتصاميم حملات ومواد تسويقية تساعد العلامات الطموحة على الظهور بمصداقية واتساق والاستعداد للنمو.',
  'Graphic design campaign': 'حملة تصميم جرافيكي', 'Responsive website development project': 'مشروع تطوير موقع متجاوب',
  'Mobile application displayed on a smartphone': 'تطبيق جوال معروض على هاتف ذكي', 'Digital advertising campaign': 'حملة إعلانية رقمية',
  'SEO Services': 'خدمات تحسين محركات البحث', 'Search visibility that compounds into': 'ظهور في البحث يتراكم ليحقق', 'sustainable growth.': 'نمواً مستداماً.',
  'We improve the technical health, relevance, and authority of your website so the right customers find your business when they are ready to act.': 'نحسّن السلامة التقنية لموقعك وملاءمته وموثوقيته ليجد العملاء المناسبون أعمالك عندما يكونون مستعدين لاتخاذ القرار.',
  'SEO analytics dashboard': 'لوحة تحليلات تحسين محركات البحث', 'UI UX interface design': 'تصميم واجهة وتجربة المستخدم',
  'Customer shopping online': 'عميل يتسوق عبر الإنترنت',
  'We shape footage into focused content with pacing, sound, color, motion, and platform-ready formats that hold attention from the first frame.': 'نحوّل اللقطات إلى محتوى مركز يجمع الإيقاع والصوت والألوان والحركة وصيغاً ملائمة للمنصات تحافظ على الانتباه منذ الإطار الأول.',
  'Professional video editing workstation': 'محطة مونتاج فيديو احترافية',
  'From concept and direction to filming and delivery, we produce professional video that gives brands, products, and events a compelling presence.': 'من الفكرة والإخراج إلى التصوير والتسليم، ننتج فيديو احترافياً يمنح العلامات والمنتجات والفعاليات حضوراً مؤثراً.',
  'Professional cinema camera': 'كاميرا سينمائية احترافية',
  'Beginner Friendly Course': 'دورة مناسبة للمبتدئين', 'Enroll Now': 'سجّل الآن', 'View Curriculum': 'عرض المنهج', 'E-Commerce Course': 'دورة التجارة الإلكترونية',
  'Shopify': 'شوبيفاي', 'Amazon': 'أمازون', 'Dropship': 'دروبشيب', 'Ads': 'إعلانات',
  'AVG. CONVERSION RATE +85%': 'متوسط التحويل +85%', 'PAID ADS ROAS 5.2x': 'عائد الإعلانات 5.2x', 'CART RECOVERY +40%': 'استعادة السلات +40%', 'STORE LAUNCH IN 14 DAYS': 'إطلاق المتجر خلال 14 يوماً', 'ON-TIME FULFILLMENT 99%': 'تنفيذ في الموعد 99%', 'CUSTOMER RETENTION +60%': 'الاحتفاظ بالعملاء +60%',
  "What You'll Learn": 'ما ستتعلمه', 'Build, launch, and scale a profitable online store': 'ابنِ وأطلق ووسّع متجراً إلكترونياً مربحاً',
  'Store Setup': 'إعداد المتجر', 'Launch on Shopify, WooCommerce, or Amazon': 'أطلق متجرك على شوبيفاي أو ووكومرس أو أمازون',
  'Product Sourcing': 'اختيار المنتجات', 'Find and manage profitable products': 'اعثر على منتجات مربحة وأدرها',
  'Run Facebook, Instagram & Google Ads': 'شغّل إعلانات فيسبوك وإنستغرام وجوجل', 'Branding & Design': 'الهوية والتصميم', 'Build a store that converts visitors': 'ابنِ متجراً يحوّل الزوار إلى عملاء',
  'Order Fulfillment': 'تنفيذ الطلبات', 'Manage shipping, payments & service': 'أدر الشحن والمدفوعات والخدمة', 'Analytics & Growth': 'التحليلات والنمو', 'Track sales and optimize performance': 'تابع المبيعات وحسّن الأداء',
  'Course Modules': 'وحدات الدورة', 'Store Setup & Platform Selection': 'إعداد المتجر واختيار المنصة', 'Choose the right platform and get your store live, fast.': 'اختر المنصة المناسبة وأطلق متجرك بسرعة.',
  'Product Research & Supplier Sourcing': 'بحث المنتجات واختيار الموردين', 'Find winning products and reliable suppliers to sell with confidence.': 'اعثر على منتجات ناجحة وموردين موثوقين لتبيع بثقة.',
  'Branding & Paid Advertising': 'الهوية والإعلانات المدفوعة', 'Build a brand people trust, then drive traffic that converts.': 'ابنِ علامة يثق بها الناس ثم اجذب زيارات تحقق مبيعات.',
  'Order Fulfillment & Customer Retention': 'تنفيذ الطلبات والاحتفاظ بالعملاء', 'Deliver a great experience that keeps customers coming back.': 'قدّم تجربة مميزة تشجع العملاء على العودة.',
  'E-Commerce order packaging and fulfillment': 'تغليف وتنفيذ طلبات التجارة الإلكترونية', 'Who This Course Is For': 'لمن هذه الدورة',
  'Beginners who want to start an online business': 'المبتدئون الراغبون في بدء مشروع إلكتروني', 'Entrepreneurs taking their business online': 'رواد الأعمال الذين ينقلون أعمالهم إلى الإنترنت', 'Freelancers wanting to add e-commerce skills': 'المستقلون الراغبون في اكتساب مهارات التجارة الإلكترونية', 'Anyone interested in dropshipping or Amazon selling': 'كل مهتم بالدروبشيب أو البيع عبر أمازون',
  "What You'll Get": 'ما ستحصل عليه', 'Step-by-step video tutorials': 'دروس فيديو خطوة بخطوة', 'Real store setup walkthroughs': 'تطبيق عملي لإعداد متجر حقيقي', 'Certificate of completion': 'شهادة إتمام', 'Lifetime access to materials': 'وصول دائم إلى المواد',
  'Start your e-commerce journey today and build a business that earns while you sleep.': 'ابدأ رحلتك في التجارة الإلكترونية اليوم وابنِ مشروعاً يحقق الدخل باستمرار.',
  'Keep Going': 'واصل التعلّم', 'Related Courses': 'دورات ذات صلة', 'Read More': 'اقرأ المزيد', 'Beginner': 'مبتدئ', 'Growth': 'نمو', 'Career': 'مسار مهني', 'Technical': 'تقني', 'Design': 'تصميم',
  'SEO (Search Engine Optimization)': 'تحسين محركات البحث', 'Learn to rank your ecommerce store on Google and drive free organic traffic to your products.': 'تعلّم رفع ترتيب متجرك في جوجل وجذب زيارات عضوية مجانية إلى منتجاتك.',
  'Master digital marketing strategies including social media, email, and paid ads.': 'أتقن استراتيجيات التسويق الرقمي بما فيها التواصل الاجتماعي والبريد والإعلانات المدفوعة.',
  'Freelancing': 'العمل الحر', 'This freelancing course is designed for individuals who want to start their online career.': 'صُممت دورة العمل الحر لمن يريد بدء مسيرته المهنية عبر الإنترنت.',
  'Business Development': 'تطوير الأعمال', 'This Business Development Course is perfect for anyone who wants to grow their business.': 'دورة تطوير الأعمال مناسبة لكل من يريد تنمية أعماله.',
  'Master HTML, CSS, JavaScript and WordPress to build responsive, modern websites from scratch.': 'أتقن HTML وCSS وJavaScript وWordPress لبناء مواقع حديثة ومتجاوبة من الصفر.',
  'Learn user interface and experience design using Figma and modern design principles.': 'تعلّم تصميم واجهة وتجربة المستخدم باستخدام Figma ومبادئ التصميم الحديثة.',
  'Trusted Partner': 'شريك موثوق', 'Why Decasofts?': 'لماذا ديكاسوفت؟', '10+ years of industry experience': 'أكثر من 10 سنوات من الخبرة', 'ISO 27001-certified for quality service': 'معتمدون وفق ISO 27001 لجودة الخدمة', 'Over 50+ certified developers': 'أكثر من 50 مطوراً معتمداً', '500+ Successful Projects': 'أكثر من 500 مشروع ناجح', 'Multiple award-winning agency': 'وكالة حائزة على عدة جوائز', 'Result-oriented approach': 'نهج يركز على النتائج', 'Certified by Clutch.co & G2.com': 'معتمدون من Clutch.co وG2.com', 'AWS Certified Engineers': 'مهندسون معتمدون من AWS',
  'BOOK A FREE CONSULTATION': 'احجز استشارة مجانية', 'Message Sent!': 'تم إرسال الرسالة!', "We'll get back to you shortly.": 'سنتواصل معك قريباً.', 'Send another message': 'إرسال رسالة أخرى', 'Get in touch': 'تواصل معنا',
  'First Name': 'الاسم الأول', 'Last Name': 'اسم العائلة', 'Email': 'البريد الإلكتروني', 'Phone Number': 'رقم الهاتف', 'Course': 'الدورة', 'Batch': 'المجموعة', 'Message': 'الرسالة', 'Select Course': 'اختر الدورة', 'Select Batch': 'اختر المجموعة', 'Morning Batch': 'المجموعة الصباحية', 'Evening Batch': 'المجموعة المسائية', 'Sending...': 'جارٍ الإرسال...', 'Send Message': 'إرسال الرسالة', 'Something went wrong. Please try again.': 'حدث خطأ. يرجى المحاولة مجدداً.',
  'Shopify Store Development': 'تطوير متجر شوبيفاي',
  'Collaboration': 'التعاون', 'Did you get stuck in something?': 'هل واجهتك مشكلة؟', "Let's collaborate & conquer.": 'لنتعاون ونتجاوزها.',
  "Our creative team specializes in solving all your digital challenges. With the expertise of our UI/UX consultants, we're here to elevate your business and enhance user experiences.": 'يتخصص فريقنا الإبداعي في حل تحدياتك الرقمية. وبخبرة مستشاري واجهة وتجربة المستخدم نساعدك على تطوير أعمالك وتحسين تجارب المستخدمين.',
  'Please fill in all fields.': 'يرجى تعبئة جميع الحقول.', 'Scroll left': 'تمرير إلى اليسار', 'Scroll right': 'تمرير إلى اليمين',
  'Web': 'تطوير', 'Development': 'الويب',
  'Master the essentials of web development and WordPress with our beginner-friendly course. Learn HTML, CSS, and JavaScript, then dive into WordPress theme customization and development — build and launch real-world projects with confidence.': 'أتقن أساسيات تطوير الويب وWordPress في دورة مناسبة للمبتدئين. تعلّم HTML وCSS وJavaScript ثم تخصيص قوالب WordPress وتطويرها، وابنِ مشاريع حقيقية وأطلقها بثقة.',
  'Build and launch real websites, from scratch': 'ابنِ مواقع حقيقية وأطلقها من الصفر', 'HTML5 & CSS3': 'HTML5 وCSS3', 'Structure and style modern web pages': 'ابنِ صفحات ويب حديثة ونسّقها', 'JavaScript': 'جافاسكربت', 'Add interactivity and dynamic behavior': 'أضف التفاعل والسلوك الديناميكي', 'Responsive Layouts': 'تخطيطات متجاوبة', 'Build mobile-friendly websites': 'ابنِ مواقع ملائمة للجوال', 'WordPress Themes': 'قوالب WordPress', 'Customize themes and use plugins': 'خصّص القوالب واستخدم الإضافات', 'Launch a Website': 'إطلاق موقع', 'Develop and ship your own WordPress site': 'طوّر موقع WordPress الخاص بك وأطلقه', 'Git & GitHub': 'Git وGitHub', 'Collaborate like a professional developer': 'تعاون كمطور محترف',
  'HTML5 & CSS3 Foundations': 'أساسيات HTML5 وCSS3', 'Structure and style pages with modern, clean markup.': 'أنشئ صفحات بهيكل حديث ونظيف ونسّقها.', 'JavaScript & Interactive Layouts': 'جافاسكربت والتخطيطات التفاعلية', 'Bring pages to life with logic and interactivity.': 'اجعل الصفحات حيوية بالمنطق والتفاعل.', 'WordPress Theme Customization': 'تخصيص قوالب WordPress', 'Adapt themes and plugins to fit any project.': 'عدّل القوالب والإضافات لتناسب أي مشروع.', 'WordPress Development & Git/GitHub': 'تطوير WordPress وGit/GitHub', 'Build, version, and launch a real website.': 'ابنِ موقعاً حقيقياً وأدر إصداراته وأطلقه.', 'Beginners with no prior coding experience': 'مبتدئون بلا خبرة برمجية سابقة', 'Freelancers & designers': 'المستقلون والمصممون', 'Entrepreneurs & content creators': 'رواد الأعمال وصنّاع المحتوى', 'Future WordPress developers': 'مطورو WordPress المستقبليون', 'Real-world projects': 'مشاريع من العالم الحقيقي', 'Master web design and WordPress development — no coding experience needed.': 'أتقن تصميم الويب وتطوير WordPress دون الحاجة إلى خبرة برمجية.',

  'Digital': 'الرقمي', 'Learn the essential skills of digital marketing with a hands-on, beginner-friendly course. Master SEO, social media, Google Ads, and email marketing to grow your brand and drive real online results.': 'تعلّم مهارات التسويق الرقمي الأساسية في دورة عملية مناسبة للمبتدئين. أتقن تحسين البحث والتواصل الاجتماعي وإعلانات جوجل والتسويق بالبريد لتنمية علامتك وتحقيق نتائج فعلية.', 'Unlock the skills to drive online success': 'اكتسب المهارات اللازمة للنجاح عبر الإنترنت',
  'SEO': 'تحسين البحث', 'Improve rankings & organic visibility': 'حسّن الترتيب والظهور العضوي', 'Social Media': 'وسائل التواصل الاجتماعي', 'Grow audiences that actually engage': 'نمِّ جمهوراً يتفاعل فعلياً', 'Google Ads & PPC': 'إعلانات جوجل والدفع بالنقرة', 'Run campaigns that convert': 'شغّل حملات تحقق التحويلات', 'Email Marketing Automation': 'أتمتة التسويق بالبريد', 'Automate nurture & sales sequences': 'أتمت رعاية العملاء ومسارات البيع', 'Content Marketing': 'تسويق المحتوى', 'Build a content engine that lasts': 'ابنِ منظومة محتوى مستدامة', 'Analytics': 'التحليلات', 'Track, measure, and optimize results': 'تابع النتائج وقِسها وحسّنها',
  'SEO & Social Media Marketing': 'تحسين البحث والتسويق الاجتماعي', 'Rank on Google and build a presence where your audience already spends time.': 'تصدّر نتائج جوجل وابنِ حضوراً حيث يوجد جمهورك.', 'Google Ads & Email Marketing': 'إعلانات جوجل والتسويق بالبريد', 'Pair paid acquisition with owned channels for compounding returns.': 'ادمج الاكتساب المدفوع مع قنواتك لتحقيق عائد متزايد.', 'Content Creation & Influencer Marketing': 'صناعة المحتوى والتسويق بالمؤثرين', 'Produce content people share, and partner with voices people trust.': 'أنشئ محتوى يشاركه الناس وتعاون مع أصوات يثقون بها.', 'Google Analytics & Marketing Funnels': 'تحليلات جوجل ومسارات التسويق', 'Turn raw data into decisions, and visitors into customers.': 'حوّل البيانات إلى قرارات والزوار إلى عملاء.', 'Beginners': 'المبتدئون', 'Entrepreneurs & business owners': 'رواد الأعمال وأصحاب المشاريع', 'Aspiring marketers': 'المسوقون الطموحون', 'Anyone growing a brand online': 'كل من ينمّي علامة عبر الإنترنت', 'Step-by-step tutorials': 'دروس خطوة بخطوة', 'Master DM and grow your brand, business, or career.': 'أتقن التسويق الرقمي ونمِّ علامتك أو أعمالك أو مسيرتك.',

  'Graphic': 'التصميم', 'Designing': 'الجرافيكي', 'Learn the art of visual storytelling with our Graphic Designing course. Master tools like Photoshop and Illustrator, create stunning designs, and build a portfolio that stands out — perfect for beginners and creatives alike.': 'تعلّم فن السرد البصري في دورة التصميم الجرافيكي. أتقن Photoshop وIllustrator وأنشئ تصاميم مبهرة وملف أعمال مميزاً، وهي مناسبة للمبتدئين والمبدعين.', 'Unlock your creative potential': 'أطلق إمكاناتك الإبداعية', 'Graphic Designing Course': 'دورة التصميم الجرافيكي',
  'Color & Typography': 'الألوان والخطوط', 'Master color theory, layout, and composition': 'أتقن نظرية الألوان والتخطيط والتكوين', 'Photoshop & Illustrator': 'Photoshop وIllustrator', 'Mastery of industry-standard design tools': 'أتقن أدوات التصميم المعتمدة في المجال', 'Logo & Brand Identity': 'الشعار وهوية العلامة', 'Design logos and identities that stand out': 'صمّم شعارات وهويات مميزة', 'Social Media & Print': 'التواصل الاجتماعي والطباعة', 'Create posters, brochures, and social content': 'أنشئ ملصقات وكتيبات ومحتوى اجتماعياً', 'UI/UX Fundamentals': 'أساسيات واجهة وتجربة المستخدم', 'Intro to modern web and mobile design': 'مقدمة في تصميم الويب والجوال الحديث', 'Portfolio & Freelancing': 'ملف الأعمال والعمل الحر', 'Build a portfolio and land your first clients': 'ابنِ ملف أعمال واحصل على عملائك الأوائل',
  'Design Foundations & Color Theory': 'أساسيات التصميم ونظرية الألوان', 'Build a strong base in typography, layout, and composition.': 'ابنِ أساساً قوياً في الخطوط والتخطيط والتكوين.', 'Adobe Photoshop & Illustrator': 'Adobe Photoshop وIllustrator', 'Get hands-on with the tools every designer relies on.': 'تدرّب عملياً على الأدوات التي يعتمد عليها كل مصمم.', 'Logo, Brand & Social Media Design': 'تصميم الشعارات والعلامات والتواصل الاجتماعي', 'Craft identities and content that capture attention.': 'اصنع هويات ومحتوى يجذبان الانتباه.', 'UI/UX Basics & Portfolio Building': 'أساسيات UI/UX وبناء ملف الأعمال', 'Step into product design and prep for freelance work.': 'ابدأ تصميم المنتجات واستعد للعمل الحر.', 'Aspiring graphic designers': 'مصممو الجرافيك الطموحون', 'Content creators, marketers & entrepreneurs': 'صنّاع المحتوى والمسوقون ورواد الأعمال', 'Students & professionals learning visual design': 'الطلاب والمحترفون الذين يتعلمون التصميم البصري', 'Anyone wanting to improve their creative output': 'كل من يريد تحسين إنتاجه الإبداعي', 'Hands-on, real-world design projects': 'مشاريع تصميم عملية واقعية', 'Downloadable templates & resources': 'قوالب وموارد قابلة للتنزيل', 'Create professional, eye-catching designs that elevate your brand.': 'أنشئ تصاميم احترافية جذابة ترتقي بعلامتك.',

  'Videography Course': 'دورة التصوير بالفيديو', 'Master the art of video production with our hands-on Videography course. Learn camera operation, lighting, professional shooting skills, and editing using industry-standard software — everything you need to create compelling videos for brands, social media, and film.': 'أتقن فن إنتاج الفيديو في دورتنا العملية. تعلّم تشغيل الكاميرا والإضاءة والتصوير الاحترافي والمونتاج ببرامج معتمدة، وكل ما تحتاجه لصناعة فيديوهات مؤثرة للعلامات والتواصل الاجتماعي والأفلام.', 'From behind the lens to the final edit': 'من خلف العدسة إلى المونتاج النهائي',
  'Camera': 'الكاميرا', 'Lighting': 'الإضاءة', 'Editing': 'المونتاج', 'Color': 'الألوان', 'Camera Fundamentals': 'أساسيات الكاميرا', 'Master ISO, aperture, and shutter speed': 'أتقن ISO وفتحة العدسة وسرعة الغالق', 'Lighting Techniques': 'تقنيات الإضاءة', 'Indoor & outdoor setups for pro results': 'إعدادات داخلية وخارجية لنتائج احترافية', 'Audio & Sound Design': 'الصوت وتصميمه', 'Record clean audio and mix for video': 'سجّل صوتاً نقياً وامزجه للفيديو', 'Cut with Premiere Pro & DaVinci Resolve': 'حرّر باستخدام Premiere Pro وDaVinci Resolve', 'Develop a cinematic, consistent look': 'أنشئ مظهراً سينمائياً متناسقاً', 'Export & Delivery': 'التصدير والتسليم', 'Deliver final videos for every platform': 'سلّم فيديوهات نهائية لكل منصة',
  'Camera Fundamentals & Equipment': 'أساسيات الكاميرا والمعدات', 'Get comfortable behind the lens with the gear that matters.': 'تعرّف عملياً على المعدات المهمة خلف العدسة.', 'Cinematography & Composition': 'التصوير السينمائي والتكوين', 'Frame shots with intention using proven cinematic rules.': 'كوّن اللقطات بوعي باستخدام قواعد سينمائية مثبتة.', 'Lighting & Audio Production': 'إنتاج الإضاءة والصوت', 'Light scenes and capture sound like a professional crew.': 'أضئ المشاهد وسجّل الصوت كفريق محترف.', 'Editing, Color Grading & Storytelling': 'المونتاج وتدرج الألوان والسرد', 'Cut, grade, and deliver a final video that tells a story.': 'حرّر ولوّن وسلّم فيديو نهائياً يروي قصة.', 'Beginners with zero videography experience': 'مبتدئون بلا خبرة في التصوير', 'Content creators and YouTubers': 'صنّاع المحتوى واليوتيوبرز', 'Social media marketers and brand managers': 'مسوقو التواصل ومديرو العلامات', 'Freelancers offering video production services': 'المستقلون في خدمات إنتاج الفيديو', 'Real shoot & editing projects': 'مشاريع تصوير ومونتاج حقيقية', 'Become a professional videographer and bring your creative vision to life.': 'أصبح مصور فيديو محترفاً وحوّل رؤيتك الإبداعية إلى واقع.',

  'Wireframing': 'المخططات الهيكلية', 'Visual Design': 'التصميم البصري', 'Prototyping': 'النماذج التفاعلية', 'UX Foundations & Research': 'أساسيات وبحث تجربة المستخدم', 'Information Architecture': 'هندسة المعلومات', 'UI Design in Figma': 'تصميم الواجهات في Figma', 'Prototype, Test & Portfolio': 'النموذج والاختبار وملف الأعمال', 'Beginner-friendly course': 'دورة مناسبة للمبتدئين', 'Design products': 'صمّم منتجات', 'people': 'يحبها', 'love.': 'الناس.',
  'Learn the complete UI/UX process—from research and wireframes to polished Figma prototypes—and build a portfolio that shows how you solve real product problems.': 'تعلّم عملية UI/UX كاملة من البحث والمخططات إلى نماذج Figma المتقنة، وابنِ ملف أعمال يوضح كيف تحل مشكلات المنتجات الحقيقية.', 'Enroll now': 'سجّل الآن', 'View curriculum': 'عرض المنهج', 'Layers': 'الطبقات', 'Find your next trip': 'اعثر على رحلتك القادمة', 'Search destinations': 'ابحث عن وجهات', "What you'll learn": 'ما ستتعلمه', 'From blank canvas to validated product.': 'من صفحة فارغة إلى منتج تم التحقق منه.', 'Build strategic thinking and practical Figma skills together, so every screen you design has a clear reason behind it.': 'اجمع التفكير الاستراتيجي ومهارات Figma العملية ليكون لكل شاشة تصممها هدف واضح.', 'Course roadmap': 'خارطة الدورة', 'Learn by designing, not just watching.': 'تعلّم بالتصميم لا بالمشاهدة فقط.', 'Each module moves your product forward. Finish with research, a design system, an interactive prototype, and a presentation-ready case study.': 'تدفع كل وحدة منتجك إلى الأمام، وتنهي الدورة ببحث ونظام تصميم ونموذج تفاعلي ودراسة حالة جاهزة للعرض.', 'Who this course is for': 'لمن هذه الدورة', "What you'll leave with": 'ما ستخرج به',
  'Built around the': 'مصممة حول', 'Digital Marketing Course': 'دورة التسويق الرقمي', '— learn how to attract, engage, and convert customers using the latest digital marketing strategies.': '— تعلّم كيف تجذب العملاء وتتفاعل معهم وتحولهم باستخدام أحدث استراتيجيات التسويق الرقمي.', '— whether you want to shoot YouTube videos, brand commercials, or social content, this course covers everything from camera settings to advanced editing and color grading, taught by industry professionals.': '— سواء أردت تصوير فيديوهات يوتيوب أو إعلانات العلامات أو محتوى التواصل، تغطي الدورة كل شيء من إعدادات الكاميرا إلى المونتاج المتقدم وتدرج الألوان على أيدي محترفين.',
  'LANGUAGES HTML · CSS · JS · PHP': 'اللغات HTML · CSS · JS · PHP', 'RESPONSIVE SITES BUILT 200+': 'أكثر من 200 موقع متجاوب', 'WORDPRESS THEMES SHIPPED 50+': 'أكثر من 50 قالب WordPress', 'AVG. PAGE LOAD UNDER 2s': 'متوسط التحميل أقل من ثانيتين', 'GIT & GITHUB WORKFLOWS COVERED': 'تغطية مسارات Git وGitHub', 'STUDENT PROJECTS LAUNCHED 300+': 'أكثر من 300 مشروع طلابي مطلق',
  'AVG. ORGANIC TRAFFIC LIFT +180%': 'زيادة الزيارات العضوية +180%', 'PPC ROAS 4.8x': 'عائد PPC بمقدار 4.8x', 'EMAIL OPEN RATE 38%': 'معدل فتح البريد 38%', 'SOCIAL ENGAGEMENT +210%': 'التفاعل الاجتماعي +210%', 'CONVERSION RATE +65%': 'معدل التحويل +65%', 'GOOGLE ADS CTR 6.2%': 'نقرات إعلانات جوجل 6.2%',
  '500+ DESIGN PROJECTS DELIVERED': 'أكثر من 500 مشروع تصميم', 'TOOLS PS · AI · ID · XD': 'الأدوات PS · AI · ID · XD', 'CLIENT SATISFACTION 96%': 'رضا العملاء 96%', 'PORTFOLIO PIECES 10+': 'أكثر من 10 أعمال للملف', 'FREELANCE-READY IN 8 WEEKS': 'جاهز للعمل الحر خلال 8 أسابيع', 'BRAND IDENTITIES CRAFTED 200+': 'أكثر من 200 هوية مصممة',
  'CAMERA SETUPS DSLR · MIRRORLESS · GIMBAL': 'معدات الكاميرا DSLR · بدون مرآة · مثبت', 'EDITING SOFTWARE PREMIERE · RESOLVE': 'برامج المونتاج PREMIERE · RESOLVE', 'STUDENT PROJECTS DELIVERED 300+': 'أكثر من 300 مشروع طلابي', '4K EXPORT READY': 'جاهز للتصدير بدقة 4K', 'SHOOT-TO-EDIT TIME -50%': 'وقت التصوير إلى المونتاج -50%', 'STUDENT SHORTS PUBLISHED 150+': 'أكثر من 150 فيديو قصير منشور',
  // Courses listing page
  'Explore Our Tracks': 'استكشف مساراتنا', 'Courses That': 'دورات تبني', 'Build': 'مستقبلاً', 'Careers.': 'مهنياً.',
  "At DecaSofts, we provide industry-focused courses in technology, development, and digital innovation. Whether you're a beginner or a pro, our expert-led training offers hands-on learning with real-world applications.": 'نقدم في DecaSofts دورات متخصصة في التقنية والتطوير والابتكار الرقمي. سواء كنت مبتدئاً أو محترفاً، يمنحك تدريبنا بإشراف الخبراء تعلماً عملياً من خلال تطبيقات واقعية.',
  'Talk to Us': 'تحدث معنا',
  'Kickstart your journey in Web Development — build responsive, modern sites from scratch.': 'ابدأ رحلتك في تطوير الويب وابنِ مواقع حديثة ومتجاوبة من الصفر.',
  "Grow your own or your clients' pages and turn followers into paying customers.": 'نمِّ صفحاتك أو صفحات عملائك وحوّل المتابعين إلى عملاء فعليين.',
  'Unlock your creative potential with a complete guide to mastering visual design.': 'أطلق إمكاناتك الإبداعية من خلال دليل متكامل لإتقان التصميم البصري.',
  'Unlock the skills to drive online success and grow brands across channels.': 'اكتسب المهارات اللازمة لتحقيق النجاح الرقمي وتنمية العلامات عبر مختلف القنوات.',
  'Capture your story with professional editing that creates engaging, high-quality visuals.': 'قدّم قصتك بمونتاج احترافي يصنع محتوى بصرياً جذاباً وعالي الجودة.',
  'Research, wireframe and prototype intuitive digital products using Figma.': 'ابحث وصمم المخططات والنماذج لمنتجات رقمية سهلة الاستخدام عبر Figma.',
  '8-Week Course': 'دورة 8 أسابيع', '6-Week Course': 'دورة 6 أسابيع', '4-Week Course': 'دورة 4 أسابيع',
  'View →': 'عرض ←', '← swipe to see all courses →': '← اسحب لمشاهدة جميع الدورات →',
  'About DecaSoft': 'عن DecaSoft', 'Building career-ready': 'نبني', 'digital talent': 'كفاءات رقمية جاهزة للعمل', 'through practical training.': 'من خلال تدريب عملي.',
  'DecaSofts is a digital agency and training studio helping students, freelancers and business owners turn modern digital skills into real careers — through hands-on courses in web development, marketing, design, and content creation, taught by the same team that builds real client projects.': 'DecaSofts وكالة رقمية واستوديو تدريبي يساعد الطلاب والمستقلين وأصحاب الأعمال على تحويل المهارات الرقمية الحديثة إلى مسارات مهنية حقيقية، عبر دورات عملية في تطوير الويب والتسويق والتصميم وصناعة المحتوى يقدمها الفريق نفسه الذي ينفذ مشاريع العملاء.',
  'Course Tracks': 'مسارات تدريبية', 'Hands-On': 'تدريب عملي', 'Global Offices': 'مكاتب عالمية',
  'Enroll Now →': 'سجّل الآن ←', 'Student Reviews': 'آراء الطلاب', 'Reviews From Students': 'مراجعات طلابنا',
  'Real feedback from students who completed our DecaSofts training programs.': 'آراء حقيقية من طلاب أكملوا برامج DecaSofts التدريبية.',
  'Content Creator': 'صانع محتوى', 'Page Manager': 'مدير صفحات', 'Digital Marketer': 'مسوق رقمي', 'Student': 'طالب',
  'Designer': 'مصمم', 'Educator': 'مدرّس', 'Tech Enthusiast': 'مهتم بالتقنية',
  'Web Development course ka pura A to Z seekha. Pehli hi mahine job mil gayi!': 'تعلمت دورة تطوير الويب كاملة من البداية إلى النهاية، وحصلت على وظيفة في الشهر الأول!',
  'Social Media Marketing se page ke views 10x ho gaye. Trainers bohat helpful the.': 'زادت مشاهدات الصفحة عشرة أضعاف بفضل دورة التسويق عبر التواصل، وكان المدربون متعاونين جداً.',
  'SEO strategy se organic traffic double ho gaya. Highly recommended.': 'ضاعفت استراتيجية تحسين البحث الزيارات العضوية. أوصي بالدورة بشدة.',
  'Step by step practical sessions the. Ab khud website manage kar leti hun.': 'كانت الجلسات عملية خطوة بخطوة، وأصبحت الآن أدير الموقع بنفسي.',
  'Graphic Designing course se apna freelance business start kiya.': 'بدأت عملي المستقل بعد دورة التصميم الجرافيكي.',
  'Apne lectures mein web dev concepts use kar raha hun. Students bohat khush hain.': 'أستخدم مفاهيم تطوير الويب في محاضراتي والطلاب سعداء جداً.',
  'Digital Marketing ke hooks aur captions ne reach badha di.': 'ساعدتني أساليب التسويق الرقمي والعناوين على زيادة الوصول.',
  'Cutting-edge tools ka practical use seekha. 10/10 course.': 'تعلمت الاستخدام العملي لأحدث الأدوات. دورة ممتازة 10/10.',
  'View All Reviews →': 'عرض جميع المراجعات ←', 'Write a Review ★': 'اكتب مراجعة ★',
  'Frequently Asked': 'الأسئلة', 'Questions': 'الشائعة', 'Everything you need to know about DecaSofts training.': 'كل ما تحتاج معرفته عن تدريب DecaSofts.',
  'What courses does DecaSofts offer?': 'ما الدورات التي تقدمها DecaSofts؟',
  'We offer Web Development, Social Media Marketing, SEO, Graphic Designing, Digital Marketing, and Video Editing — all taught by our in-house team who also build real client projects.': 'نقدم تطوير الويب والتسويق عبر التواصل وتحسين محركات البحث والتصميم الجرافيكي والتسويق الرقمي ومونتاج الفيديو، ويقدمها فريقنا الذي ينفذ أيضاً مشاريع حقيقية للعملاء.',
  'Where are the classes held?': 'أين تُعقد الدروس؟',
  'Classes are held at our Faisalabad studio, with remote/online options available for students joining from Dubai or elsewhere.': 'تُعقد الدروس في استوديو فيصل آباد، مع خيارات تعلم عن بعد للطلاب من دبي وأماكن أخرى.',
  'Do I need any prior experience to join?': 'هل أحتاج إلى خبرة سابقة للانضمام؟',
  'No — every track is designed to take complete beginners from zero to job-ready, with hands-on projects at every stage.': 'لا، فقد صُمم كل مسار لنقل المبتدئ من الصفر إلى الجاهزية للعمل، مع مشاريع عملية في كل مرحلة.',
  'How long is each training program?': 'ما مدة كل برنامج تدريبي؟',
  'Program length varies by track, from 4-Week intensives (SEO, Video Editing) to 8-Week deep-dives (Web Development, Digital Marketing).': 'تختلف المدة حسب المسار، من برامج مكثفة لأربعة أسابيع إلى برامج متعمقة لثمانية أسابيع.',
  'Will I get a certificate after completion?': 'هل سأحصل على شهادة بعد الإكمال؟',
  'Yes, every student who completes their course and final project receives a DecaSofts certificate of completion.': 'نعم، يحصل كل طالب يكمل الدورة والمشروع النهائي على شهادة إتمام من DecaSofts.',
  'What is the fee structure?': 'ما نظام الرسوم؟',
  'Fees vary by course and are billed per program in easy installments. Reach out to our team on WhatsApp or via the contact form for current pricing.': 'تختلف الرسوم حسب الدورة ويمكن دفعها بأقساط ميسرة. تواصل معنا عبر واتساب أو نموذج الاتصال لمعرفة الأسعار الحالية.',
  'How do I register for a batch?': 'كيف أسجل في دفعة؟',
  'Pick a course, click Enroll Now, and our team will reach out within hours to confirm your batch and schedule.': 'اختر الدورة واضغط سجّل الآن، وسيتواصل فريقنا معك خلال ساعات لتأكيد الدفعة والجدول.',
  'Do you offer refunds?': 'هل توفرون استرداد الرسوم؟',
  "We offer a refund window in the first week of any program if the course isn't the right fit for you — details are shared at enrollment.": 'نوفر فترة لاسترداد الرسوم خلال الأسبوع الأول إذا لم تكن الدورة مناسبة لك، وتُوضح التفاصيل عند التسجيل.',

  // Services landing page
  'Digital services for ambitious brands': 'خدمات رقمية للعلامات التجارية الطموحة',
  'One expert team to turn your ideas into': 'فريق واحد من الخبراء يحوّل أفكارك إلى',
  'measurable growth.': 'نمو قابل للقياس.',
  'Strategy, design, technology, and marketing—connected under one roof to build stronger brands and better digital experiences.': 'الاستراتيجية والتصميم والتقنية والتسويق ضمن فريق واحد لبناء علامات أقوى وتجارب رقمية أفضل.',
  'Discuss your project': 'ناقش مشروعك معنا', 'Explore services': 'استكشف خدماتنا',
  'Strategy-first thinking': 'تفكير يبدأ بالاستراتيجية', 'Specialist delivery teams': 'فرق تنفيذ متخصصة', 'Transparent communication': 'تواصل شفاف',
  'Digital agency team planning a client project': 'فريق وكالة رقمية يخطط لمشروع عميل',
  'Our capabilities': 'قدراتنا', 'Built to solve the whole digital challenge.': 'حلول متكاملة لكل تحدٍ رقمي.',
  'Choose a focused service or bring us a complex challenge. Our teams collaborate across disciplines so every touchpoint feels consistent and works toward the same outcome.': 'اختر خدمة متخصصة أو شاركنا تحدياً معقداً. تتعاون فرقنا عبر مختلف التخصصات لتقديم تجربة متسقة تحقق هدفاً واحداً.',
  'Fast, responsive websites and web applications engineered around your business goals.': 'مواقع وتطبيقات ويب سريعة ومتجاوبة مصممة حول أهداف أعمالك.',
  'Intuitive iOS, Android, and cross-platform applications built for performance and scale.': 'تطبيقات سهلة الاستخدام لنظامي iOS وAndroid ومتعددة المنصات، مبنية للأداء والتوسع.',
  'Focused campaigns that connect strategy, creative, media, and measurable growth.': 'حملات مركزة تجمع الاستراتيجية والإبداع والإعلام لتحقيق نمو قابل للقياس.',
  'Technical and content-led search strategies that build sustainable online visibility.': 'استراتيجيات بحث تقنية وقائمة على المحتوى تبني ظهوراً رقمياً مستداماً.',
  'Clear, accessible product experiences shaped around real users and real outcomes.': 'تجارب منتجات واضحة وسهلة الوصول مصممة حول مستخدمين حقيقيين ونتائج فعلية.',
  'E-commerce & Shopify': 'التجارة الإلكترونية وShopify',
  'Conversion-focused storefronts that make discovering and buying products effortless.': 'متاجر تركز على التحويل وتجعل اكتشاف المنتجات وشراءها أكثر سهولة.',
  'Distinctive identities and campaign visuals that make brands credible and memorable.': 'هويات مميزة وتصاميم حملات تجعل العلامات موثوقة وراسخة في الذاكرة.',
  'Raw footage transformed into polished stories built to hold audience attention.': 'تحويل اللقطات الخام إلى قصص متقنة تحافظ على انتباه الجمهور.',
  'Professional video production that captures products, people, and stories with purpose.': 'إنتاج فيديو احترافي يوثق المنتجات والأشخاص والقصص بوضوح وهدف.',
  'Custom websites': 'مواقع مخصصة', 'Web applications': 'تطبيقات ويب', 'Maintenance': 'الصيانة',
  'iOS apps': 'تطبيقات iOS', 'Android apps': 'تطبيقات Android', 'Cross-platform': 'متعدد المنصات',
  'Paid advertising': 'إعلانات مدفوعة', 'Social media': 'التواصل الاجتماعي', 'Content strategy': 'استراتيجية المحتوى',
  'Content SEO': 'تحسين المحتوى',
  'User research': 'بحث المستخدمين', 'Interface design': 'تصميم الواجهات', 'Design systems': 'أنظمة التصميم',
  'Shopify stores': 'متاجر Shopify', 'Custom commerce': 'تجارة مخصصة', 'Integrations': 'التكاملات',
  'Brand identity': 'هوية العلامة', 'Social creative': 'تصاميم اجتماعية', 'Packaging': 'التغليف',
  'Motion graphics': 'رسوم متحركة', 'Social video': 'فيديو اجتماعي',
  'Brand films': 'أفلام العلامات', 'Commercials': 'إعلانات تجارية', 'Event coverage': 'تغطية الفعاليات',
  'Explore service': 'استكشف الخدمة',
  'How we work': 'كيف نعمل', 'A clear process. No unnecessary complexity.': 'عملية واضحة بلا تعقيد غير ضروري.',
  'You always know what we are doing, why it matters, and what comes next.': 'ستعرف دائماً ما الذي نعمل عليه، ولماذا هو مهم، وما الخطوة التالية.',
  'Understand': 'نفهم', 'We learn your business, audience, challenges, and definition of success.': 'نتعرف إلى أعمالك وجمهورك وتحدياتك ومعايير النجاح لديك.',
  'Strategize': 'نخطط', 'We turn the findings into a focused roadmap with clear priorities.': 'نحوّل ما تعلمناه إلى خارطة طريق مركزة ذات أولويات واضحة.',
  'Our specialists execute, review, and refine every deliverable collaboratively.': 'ينفذ متخصصونا كل مخرج ويراجعونه ويحسنونه بروح تعاونية.',
  'Grow': 'ننمو', 'We launch, measure, improve, and support the next stage of your growth.': 'نطلق ونقيس ونحسن وندعم المرحلة التالية من نموك.',
  'Why Decasoft': 'لماذا Decasoft', 'One accountable partner from strategy to delivery.': 'شريك مسؤول واحد من الاستراتيجية إلى التسليم.',
  'Instead of coordinating multiple vendors, work with a connected team that understands the complete customer journey and keeps every decision aligned.': 'بدلاً من تنسيق عدة مزودين، اعمل مع فريق مترابط يفهم رحلة العميل كاملة ويحافظ على اتساق كل قرار.',
  'Senior specialist talent': 'خبرات تخصصية رفيعة', 'Business-focused recommendations': 'توصيات تركز على الأعمال',
  'Responsive project management': 'إدارة مشاريع سريعة الاستجابة', 'Scalable long-term support': 'دعم طويل الأمد قابل للتوسع',
  'Learn more about us': 'اعرف المزيد عنا', 'A website project delivered by Decasoft': 'مشروع موقع نفذته Decasoft',
  "Have a challenge in mind? Let's find the right way forward.": 'لديك تحدٍ؟ لنجد معاً الطريق الأنسب للمضي قدماً.',
  'Book a free consultation': 'احجز استشارة مجانية',

  // Remaining Graphic Designing course fragments
  '— a complete guide to mastering visual communication, from design fundamentals to industry-standard tools and a portfolio-ready skill set.': '— دليل متكامل لإتقان التواصل البصري، بدءاً من أساسيات التصميم ووصولاً إلى الأدوات الاحترافية ومهارات إعداد ملف أعمال جاهز.',
  'SEO Optimized Version – This course is perfect for anyone who wants to rank websites on Google.': 'دورة عملية في تحسين محركات البحث لكل من يريد رفع ترتيب المواقع في نتائج جوجل.',
  'A complete, hands-on program designed to teach you how to build and launch Shopify stores.': 'برنامج عملي متكامل يعلّمك كيفية إنشاء متاجر Shopify وإطلاقها.',

  // Case-study portfolio pages
  'Learn How We Can Make A Real Impact': 'اكتشف كيف نصنع تأثيراً حقيقياً',
  'Our': 'أبرز', 'Portfolio': 'معرض الأعمال',
  'Social Media Portfolio &': 'معرض أعمال التواصل الاجتماعي و', 'Meta Ads': 'إعلانات ميتا',
  'Logo Design': 'تصميم الشعارات',
  "Check out some of the impactful work we've done for our clients across various industries. Click any project to read the full case study.": 'تعرّف على بعض أعمالنا المؤثرة التي أنجزناها لعملائنا في قطاعات متعددة. انقر على أي مشروع لقراءة دراسة الحالة كاملة.',
  'Explore our results-driven social media campaigns and Meta advertising work — from brand-building content strategies to high-performing ad funnels that deliver real ROI. Click any project to see the full case study.': 'استكشف حملاتنا القائمة على النتائج في وسائل التواصل الاجتماعي وإعلانات ميتا، من استراتيجيات بناء العلامة التجارية إلى المسارات الإعلانية عالية الأداء التي تحقق عائداً فعلياً. انقر على أي مشروع لمشاهدة دراسة الحالة كاملة.',
  'Explore our creative design work — from brand identities and packaging to UI/UX and print collateral that brings ideas to life. Click any project to view it.': 'استكشف أعمالنا في التصميم الإبداعي، من هويات العلامات التجارية والتغليف إلى تصميم واجهة وتجربة المستخدم والمطبوعات التي تحول الأفكار إلى واقع. انقر على أي مشروع لعرضه.',
  'Explore our logo design work — from wordmarks and emblems to abstract marks that': 'استكشف أعمالنا في تصميم الشعارات، من الشعارات النصية والرموز إلى العلامات التجريدية التي',
  "capture a brand's identity in a single icon. Click any project to see the full case study.": 'تلخص هوية العلامة التجارية في رمز واحد. انقر على أي مشروع لمشاهدة دراسة الحالة كاملة.',
  'Explore our cinematic storytelling — from event coverage and brand films to product videography that brings ideas to life. Click any project to watch the video.': 'استكشف أعمالنا في السرد السينمائي، من تغطية الفعاليات وأفلام العلامات التجارية إلى تصوير المنتجات الذي يحول الأفكار إلى واقع. انقر على أي مشروع لمشاهدة الفيديو.',
  'View Case Study': 'عرض دراسة الحالة', 'View': 'عرض', 'Watch Video': 'شاهد الفيديو',
  'Start a Similar Project': 'ابدأ مشروعاً مماثلاً', 'Close': 'إغلاق',
  'Showing': 'عرض', 'of': 'من', 'projects': 'مشاريع',
  'Ready to grow your brand on social?': 'هل أنت مستعد لتنمية علامتك على وسائل التواصل؟',
  'Ready to bring your brand to life?': 'هل أنت مستعد لإحياء علامتك التجارية؟',
  "Ready to tell your brand's story?": 'هل أنت مستعد لسرد قصة علامتك التجارية؟',
  'Ready for a logo that stands out?': 'هل أنت مستعد لشعار مميز؟',
  'Lets Collaborate & Conquer :': 'لنتعاون ونحقق النجاح معاً:',
  'Our creative team specializes in building high-performing social media and Meta ad campaigns. Let’s craft a strategy that gets results for your brand.': 'يتخصص فريقنا الإبداعي في بناء حملات عالية الأداء على وسائل التواصل وإعلانات ميتا. لنصنع استراتيجية تحقق نتائج حقيقية لعلامتك.',
  'Our creative team specializes in striking visual design that makes your brand unforgettable. Let’s craft something great together.': 'يتخصص فريقنا الإبداعي في تصميمات بصرية لافتة تجعل علامتك لا تُنسى. لنصنع معاً شيئاً مميزاً.',
  'Our creative team specializes in cinematic videography that captures attention and drives results. Let’s bring your vision to the screen.': 'يتخصص فريقنا الإبداعي في تصوير سينمائي يجذب الانتباه ويحقق النتائج. لنحول رؤيتك إلى الشاشة.',
  "Our creative team specializes in crafting memorable logos that capture your brand's essence. Let’s design an identity you'll be proud of.": 'يتخصص فريقنا الإبداعي في ابتكار شعارات راسخة تعبّر عن جوهر علامتك. لنصمم هوية تفخر بها.',
  'Social Media Portfolio': 'معرض أعمال التواصل الاجتماعي',
  'Green Wood Vacation Homes Rental LLC brings a fresh, sophisticated edge to short-term rentals and holiday homes in Dubai.': 'تقدم Green Wood Vacation Homes Rental LLC تجربة عصرية وراقية للإيجارات قصيرة الأجل وبيوت العطلات في دبي.',
  'Khalifa Bakhit Real Estate LLC is a premier real estate company headquartered in Dubai, UAE.': 'شركة خليفة بخيت العقارية هي شركة رائدة يقع مقرها في دبي، الإمارات العربية المتحدة.',
  'Al Zahra Curtains is a leading provider of high-quality window treatments and home decor solutions in the UAE.': 'الزهرة للستائر مزود رائد لحلول الستائر وديكور المنازل عالية الجودة في الإمارات.',
  'MH-Albadar, based in Pakistan, provides exceptional tours and travel services, specializing in Hajj and Umrah packages.': 'تقدم MH-Albadar، ومقرها باكستان، خدمات سفر وسياحة متميزة متخصصة في باقات الحج والعمرة.',
  'Best Property marketing place in PAKISTAN': 'منصة متميزة لتسويق العقارات في باكستان.',
  'Noor Al Aweer Technical Services, we specialize in delivering innovative, high-quality glass and aluminum solutions tailored to meet the dynamic needs of modern architecture.': 'تتخصص نور العوير للخدمات الفنية في تقديم حلول مبتكرة وعالية الجودة للزجاج والألمنيوم تلائم متطلبات العمارة الحديثة.',
  'Out Loud Fashion delivers modern, trend-driven styles that empower self-expression. Designed for fashion-forward audiences, the brand combines creativity, confidence, elegance, and individuality.': 'تقدم Out Loud Fashion أزياء عصرية مواكبة للاتجاهات تعزز التعبير عن الذات، وتجمع بين الإبداع والثقة والأناقة والتميز.',
  'e-Commerce': 'التجارة الإلكترونية', 'UI/UX Design': 'تصميم واجهة وتجربة المستخدم', 'Web Design & Development': 'تصميم وتطوير المواقع',
  'Digital Marketing Web Development': 'التسويق الرقمي وتطوير المواقع', 'Landing Page': 'صفحة هبوط',
  'Load Time': 'وقت التحميل', 'Processing Time': 'وقت المعالجة', 'Departments': 'الأقسام',
  'Users Served': 'المستخدمون المستفيدون', 'Countries Shipped': 'دول الشحن', 'Page Speed': 'سرعة الصفحة',
  'Churn Reduced': 'خفض التسرب', 'User Flows': 'مسارات المستخدم', 'Organic Traffic': 'الزيارات العضوية',
  'Keywords Ranked': 'الكلمات المتصدرة', 'Revenue Growth': 'نمو الإيرادات', 'Channels': 'القنوات',
  'Email Open Rate': 'معدل فتح البريد', 'Doctors Listed': 'العناصر المدرجة', 'Bookings/Month': 'الحجوزات شهرياً',
  'Uptime': 'استمرارية التشغيل',
  'Ran a full-funnel Facebook & Instagram ad campaign that generated a 4.2x ROAS and grew followers by 60% in 90 days.': 'نفذنا حملة إعلانية متكاملة على فيسبوك وإنستغرام حققت عائداً 4.2 مرة وزادت المتابعين 60% خلال 90 يوماً.',
  'Designed and managed a content calendar across Instagram & TikTok, driving a 3x increase in organic reach.': 'صممنا وأدرنا تقويم محتوى على إنستغرام وتيك توك، مما ضاعف الوصول العضوي ثلاث مرات.',
  'Localized Meta ad campaign targeting nearby customers, resulting in a 38% increase in foot traffic.': 'حملة إعلانات ميتا محلية استهدفت العملاء القريبين ورفعت زيارات المتجر بنسبة 38%.',
  'Built brand presence from scratch across Instagram and Facebook with reels and influencer collaborations.': 'بنينا حضور العلامة من الصفر على إنستغرام وفيسبوك عبر الريلز والتعاون مع المؤثرين.',
  'Lead-generation ad funnel for gym membership sign-ups, achieving a 45% reduction in cost-per-lead.': 'مسار إعلاني لجذب اشتراكات النادي خفّض تكلفة العميل المحتمل بنسبة 45%.',
  'Full social media management including content creation and influencer outreach across 3 platforms.': 'إدارة متكاملة للتواصل الاجتماعي شملت صناعة المحتوى والتعاون مع المؤثرين عبر ثلاث منصات.',
  'B2B lead generation campaign on LinkedIn & Meta, driving 200+ qualified leads in the first quarter.': 'حملة لاستقطاب عملاء الشركات عبر لينكدإن وميتا حققت أكثر من 200 عميل محتمل مؤهل في الربع الأول.',
  'Food photography and Instagram reels strategy that boosted reservations by 30% in two months.': 'استراتيجية لتصوير الطعام وريلز إنستغرام رفعت الحجوزات بنسبة 30% خلال شهرين.',
  'Visual-first Meta ad campaign for a furniture brand, increasing online store conversions by 52%.': 'حملة إعلانات ميتا بصرية لعلامة أثاث رفعت تحويلات المتجر الإلكتروني بنسبة 52%.',
  'Glow Beauty Co. came to us looking to scale their online presence and drive consistent, profitable sales through paid social. We built a full-funnel Meta advertising strategy spanning awareness, retargeting, and conversion campaigns across Facebook and Instagram. Creative testing, audience segmentation, and continuous optimization led to a 4.2x return on ad spend and a 60% growth in their organic follower base within 90 days.': 'تواصلت معنا Glow Beauty Co. لتوسيع حضورها الرقمي وتحقيق مبيعات مدفوعة مستقرة ومربحة. أنشأنا استراتيجية إعلانات ميتا متكاملة شملت الوعي وإعادة الاستهداف والتحويل عبر فيسبوك وإنستغرام. وأدت اختبارات المواد الإبداعية وتقسيم الجمهور والتحسين المستمر إلى عائد إعلاني 4.2 مرة ونمو المتابعين العضويين 60% خلال 90 يوماً.',
  'UrbanFit Apparel needed a consistent brand voice and visual identity across their social channels. We developed a content calendar covering Instagram and TikTok, mixing product showcases, behind-the-scenes content, and trend-driven reels. The result was a 3x increase in organic reach and a noticeably stronger, more recognizable brand presence.': 'احتاجت UrbanFit Apparel إلى صوت وهوية بصرية متسقين عبر قنواتها الاجتماعية. طورنا تقويم محتوى لإنستغرام وتيك توك يجمع عروض المنتجات وكواليس العمل والريلز المواكبة للاتجاهات، فزاد الوصول العضوي ثلاثة أضعاف وأصبح حضور العلامة أقوى وأكثر تميزاً.',
  'Bloom Cafe wanted to drive more local foot traffic and online orders. We ran a hyper-local Meta ad campaign using geo-targeting and dynamic creative tailored to nearby audiences. This resulted in a 38% increase in foot traffic and a measurable lift in online order volume within the first six weeks.': 'أراد Bloom Cafe زيادة الزيارات المحلية والطلبات الإلكترونية. نفذنا حملة ميتا شديدة المحلية باستخدام الاستهداف الجغرافي ومواد إبداعية ديناميكية للجمهور القريب، فزادت زيارات المتجر 38% وارتفع حجم الطلبات خلال الأسابيع الستة الأولى.',
  'TechNest Gadgets launched with zero social presence. We built their brand from the ground up — visual identity, content pillars, reels strategy, and influencer partnerships across Instagram and Facebook. Within four months they had an engaged community and consistent product launch buzz.': 'انطلقت TechNest Gadgets بلا حضور اجتماعي. بنينا العلامة من الصفر، بما يشمل الهوية البصرية ومحاور المحتوى واستراتيجية الريلز والشراكات مع المؤثرين على إنستغرام وفيسبوك. وخلال أربعة أشهر تكوّن مجتمع متفاعل وزخم مستمر حول إطلاق المنتجات.',
  'FitZone Gym needed a reliable system for filling membership sign-ups. We designed a lead-generation ad funnel on Meta with optimized creative and landing pages, cutting their cost-per-lead by 45% while increasing total lead volume month over month.': 'احتاج FitZone Gym إلى نظام موثوق لزيادة الاشتراكات. صممنا مساراً إعلانياً لجذب العملاء عبر ميتا مع مواد وصفحات هبوط محسّنة، فخفضنا تكلفة العميل المحتمل 45% مع زيادة عدد العملاء شهراً بعد شهر.',
  'PureSkin Cosmetics partnered with us for end-to-end social media management — content creation, community engagement, and influencer outreach across Instagram, TikTok, and Facebook. The result was a stronger brand community and steady month-over-month engagement growth.': 'تعاونت PureSkin Cosmetics معنا لإدارة التواصل الاجتماعي بالكامل، من صناعة المحتوى وتفاعل المجتمع إلى التواصل مع المؤثرين عبر إنستغرام وتيك توك وفيسبوك. والنتيجة مجتمع أقوى للعلامة ونمو ثابت في التفاعل شهراً بعد شهر.',
  "NovaTech Solutions needed qualified B2B leads for their SaaS product. We built a coordinated lead-gen campaign across LinkedIn and Meta with tailored messaging for each platform's audience, generating over 200 qualified leads in the first quarter alone.": 'احتاجت NovaTech Solutions إلى عملاء شركات مؤهلين لمنتجها البرمجي. أنشأنا حملة منسقة عبر لينكدإن وميتا برسائل تناسب جمهور كل منصة، وحققنا أكثر من 200 عميل محتمل مؤهل في الربع الأول وحده.',
  'Spice Route Restaurant wanted their food to do the talking online. We produced professional food photography and a reels-first content strategy for Instagram, which boosted online reservations by 30% within two months of launch.': 'أراد Spice Route Restaurant أن يعكس حضوره الرقمي جودة أطباقه. أنتجنا تصويراً احترافياً للطعام واستراتيجية محتوى تركز على ريلز إنستغرام، فارتفعت الحجوزات الإلكترونية 30% خلال شهرين من الإطلاق.',
  'Luxe Interiors needed to turn social browsers into online buyers. We ran a visual-first Meta ad campaign showcasing their furniture collections with dynamic product ads, increasing online store conversions by 52% over the campaign period.': 'احتاجت Luxe Interiors إلى تحويل متصفحي التواصل إلى مشترين. نفذنا حملة ميتا بصرية تعرض مجموعات الأثاث بإعلانات منتجات ديناميكية، فزادت تحويلات المتجر الإلكتروني 52% خلال الحملة.',
  'ROAS': 'العائد الإعلاني', 'Follower Growth': 'نمو المتابعين', 'Duration': 'المدة',
  'Organic Reach': 'الوصول العضوي', 'Platforms': 'المنصات', 'Content Pieces': 'قطع المحتوى',
  'Foot Traffic': 'زيارات المتجر', 'Radius': 'النطاق', 'Campaign Length': 'مدة الحملة',
  'Followers Gained': 'المتابعون الجدد', 'Influencers': 'المؤثرون', 'Timeline': 'المدة الزمنية',
  'Cost Per Lead': 'تكلفة العميل المحتمل', 'Leads/Month': 'عملاء محتملون شهرياً', 'Conversion Rate': 'معدل التحويل',
  'Engagement': 'التفاعل', 'Posts/Month': 'منشورات شهرياً', 'Qualified Leads': 'عملاء محتملون مؤهلون',
  'Quarter': 'الربع', 'Reservations': 'الحجوزات', 'Reels Produced': 'مقاطع ريلز منتجة',
  'Conversions': 'التحويلات', 'Ad Sets': 'المجموعات الإعلانية',
  'Instagram': 'إنستغرام', 'Facebook': 'فيسبوك', 'Creative': 'إبداعي',
  'TikTok': 'تيك توك', 'Local Targeting': 'استهداف محلي', 'Branding': 'بناء العلامة', 'Reels': 'ريلز',
  'Influencer': 'مؤثرون', 'Lead Gen': 'جذب العملاء', 'Conversion': 'التحويل', 'Community': 'المجتمع',
  'Content': 'المحتوى', 'B2B': 'بين الشركات', 'Food Photography': 'تصوير الطعام',
  'E-commerce': 'التجارة الإلكترونية', 'Visual': 'بصري',
  '90 days': '90 يوماً', '6 weeks': '6 أسابيع', '4 months': '4 أشهر', '2 months': 'شهران',
}

type LanguageContextValue = {
  locale: Locale
  isRtl: boolean
  t: (text: string) => string
  href: (path: string) => string
  switchLocale: (nextLocale: Locale) => void
}

const LanguageContext = createContext<LanguageContextValue | null>(null)

export default function LanguageProvider({ locale, children }: { locale: Locale; children: React.ReactNode }) {
  const pathname = usePathname()
  const router = useRouter()
  const pathnameLocale = pathname.split('/')[1] ?? ''
  const activeLocale = isLocale(pathnameLocale) ? pathnameLocale : locale

  useEffect(() => {
    document.documentElement.lang = activeLocale
    document.documentElement.dir = activeLocale === 'ar' ? 'rtl' : 'ltr'
    document.cookie = `NEXT_LOCALE=${activeLocale}; path=/; max-age=31536000; SameSite=Lax`

    const verticalPosition = window.scrollY
    const resetHorizontalPosition = () => {
      document.documentElement.scrollLeft = 0
      document.body.scrollLeft = 0
      window.scrollTo({ left: 0, top: verticalPosition, behavior: 'instant' })
    }
    resetHorizontalPosition()
    const frame = requestAnimationFrame(resetHorizontalPosition)
    return () => cancelAnimationFrame(frame)
  }, [activeLocale])

  const value = useMemo<LanguageContextValue>(() => ({
    locale: activeLocale,
    isRtl: activeLocale === 'ar',
    t: (text) => activeLocale === 'ar' ? arabic[text] ?? text : text,
    href: (path) => localizeHref(path, activeLocale),
    switchLocale: (nextLocale) => {
      document.cookie = `NEXT_LOCALE=${nextLocale}; path=/; max-age=31536000; SameSite=Lax`
      document.documentElement.scrollLeft = 0
      document.body.scrollLeft = 0
      router.refresh()
    },
  }), [activeLocale, pathname, router])

  return <LanguageContext.Provider key={activeLocale} value={value}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) throw new Error('useLanguage must be used inside LanguageProvider')
  return context
}
