import Image from 'next/image'
import Link from 'next/link'
import { ArrowRight, BadgeCheck, BarChart3, Boxes, Brush, Camera, Check, Code2, Film, Gauge, Globe2, Layers3, Megaphone, MonitorSmartphone, PackageOpen, Palette, PenTool, Search, ShoppingBag, Smartphone, Sparkles, Target, TrendingUp } from 'lucide-react'

const icons = { analytics: BarChart3, boxes: Boxes, camera: Camera, code: Code2, film: Film, gauge: Gauge, globe: Globe2, layers: Layers3, marketing: Megaphone, mobile: Smartphone, responsive: MonitorSmartphone, package: PackageOpen, palette: Palette, pen: PenTool, search: Search, shop: ShoppingBag, sparkles: Sparkles, target: Target, growth: TrendingUp }
type IconName = keyof typeof icons

type Config = {
  eyebrow: string; title: string; accent: string; intro: string; hero: string; heroAlt: string
  feature: string; sectionTitle: string; services: Array<[IconName, string, string]>
  processTitle: string; workTitle: string; work: string[]; caseStudy?: string; cta: string
}

const configs = {
  'graphic-desiging': {
    eyebrow: 'Graphic Designing Services', title: 'Design that makes your brand', accent: 'impossible to ignore.',
    intro: 'We turn strategy into memorable visual identities, campaign creatives, and marketing assets that help ambitious brands look credible, consistent, and ready to grow.', hero: '/posters/1.jpeg', heroAlt: 'Graphic design campaign', feature: 'Campaign design with clarity and impact', sectionTitle: 'Everything your brand needs to show up with confidence.',
    services: [['palette','Brand Identity','Logos, color systems, typography, and guidelines built for recognition.'],['marketing','Social Media Design','Scroll-stopping posts, stories, and advertising creative for every platform.'],['package','Packaging Design','Shelf-ready packaging that communicates value and earns attention.'],['layers','Marketing Collateral','Brochures, profiles, presentations, flyers, and polished print assets.'],['pen','Illustration & Artwork','Custom illustration, icons, and artwork with a distinctive personality.'],['boxes','Digital Campaigns','Cohesive visual systems for launches, web, email, and advertising.']],
    processTitle: 'Good design starts before the first sketch.', workTitle: 'Designed to perform in the real world.', work: ['/posters/1.jpeg','/posters/10.jpeg','/posters/20.jpeg'], caseStudy: '/case-studies/graphic-design', cta: 'Ready for a visual identity that works as hard as you do?',
  },
  'web-development': {
    eyebrow: 'Web Development Services', title: 'Websites engineered to', accent: 'turn attention into growth.',
    intro: 'We design and develop fast, responsive, conversion-focused websites that give your business a stronger digital foundation and a better customer experience.', hero: '/web/outloud.png', heroAlt: 'Responsive website development project', feature: 'Fast, scalable, conversion-ready websites', sectionTitle: 'Modern web solutions built around your business.',
    services: [['code','Custom Development','Purpose-built websites and applications aligned with your workflows.'],['responsive','Responsive Experiences','Thoughtful interfaces that perform beautifully on every screen.'],['shop','E-commerce Development','Reliable online stores with intuitive, secure buying journeys.'],['gauge','Speed Optimization','Performance engineering for faster loading and stronger usability.'],['globe','CMS Solutions','Flexible systems that make publishing and content management easy.'],['boxes','Support & Maintenance','Ongoing updates, monitoring, improvements, and technical support.']],
    processTitle: 'A reliable website begins with the right technical plan.', workTitle: 'Digital experiences built to deliver results.', work: ['/web/outloud.png','/web/nooralaweer.png','/web/greenwood.png'], caseStudy: '/case-studies/website-development', cta: 'Ready to build a website that moves your business forward?',
  },
  'mobile-app-development': {
    eyebrow: 'Mobile App Development', title: 'Mobile products designed to', accent: 'earn a place on every screen.',
    intro: 'We design and develop reliable iOS and Android applications that feel intuitive, perform smoothly, and give your business a scalable mobile foundation.', hero: 'https://images.unsplash.com/photo-1551650975-87deedd944c3?w=1200&q=85', heroAlt: 'Mobile application displayed on a smartphone', feature: 'Native-quality experiences built around real users', sectionTitle: 'From product idea to polished mobile experience.',
    services: [['mobile','iOS Development','Responsive, secure applications created for the Apple ecosystem.'],['responsive','Android Development','Reliable Android experiences optimized across devices and screen sizes.'],['code','Cross-platform Apps','Efficient React Native and Flutter builds with a consistent native feel.'],['palette','Mobile UI/UX','Clear navigation and accessible interfaces designed for touch-first use.'],['boxes','API & Integrations','Secure connections to payments, CRM, analytics, maps, and business systems.'],['gauge','App Optimization','Performance, stability, testing, store readiness, and ongoing improvements.']],
    processTitle: 'Successful apps begin with the right product decisions.', workTitle: 'Mobile experiences shaped for everyday use.', work: ['https://images.unsplash.com/photo-1607252650355-f7fd0460ccdb?w=900&q=85','https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=900&q=85','https://images.unsplash.com/photo-1555774698-0b77e0d5fac6?w=900&q=85'], cta: 'Ready to turn your mobile app idea into a product people value?',
  },
  'digital-marketing': {
    eyebrow: 'Digital Marketing Services', title: 'Campaigns that reach people and', accent: 'move them to act.',
    intro: 'We connect strategy, content, media, and measurement to build awareness, generate qualified leads, and improve return on spend.', hero: '/ads-ss/1.jpeg', heroAlt: 'Digital advertising campaign', feature: 'Strategy and creative working as one', sectionTitle: 'Full-funnel marketing with measurable direction.',
    services: [['target','Paid Advertising','Focused Meta and Google campaigns for high-intent audiences.'],['marketing','Social Media Marketing','Content and community strategies that build attention and trust.'],['sparkles','Content Strategy','Useful, persuasive content aligned with the customer journey.'],['analytics','Analytics & Reporting','Clear insights that turn performance into confident decisions.'],['growth','Conversion Optimization','Campaign and landing-page improvements that increase results.'],['search','Search Marketing','Organic and paid programs that capture existing demand.']],
    processTitle: 'Strong marketing is a system, not a collection of posts.', workTitle: 'Creative campaigns grounded in performance.', work: ['/ads-ss/1.jpeg','/ads-ss/3.jpeg','/ads-ss/6.jpeg'], caseStudy: '/case-studies/social-media-marketing-meta-ads', cta: 'Ready to turn your marketing budget into measurable growth?',
  },
  seo: {
    eyebrow: 'SEO Services', title: 'Search visibility that compounds into', accent: 'sustainable growth.',
    intro: 'We improve the technical health, relevance, and authority of your website so the right customers find your business when they are ready to act.', hero: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&q=85', heroAlt: 'SEO analytics dashboard', feature: 'Search strategy built for lasting visibility', sectionTitle: 'A complete SEO program, not isolated tactics.',
    services: [['search','SEO Audits','Technical, content, authority, and competitor opportunity analysis.'],['gauge','Technical SEO','Structure, speed, crawling, indexing, schema, and Core Web Vitals.'],['pen','Content Optimization','Search-focused pages that answer genuine customer needs.'],['globe','Local SEO','Local visibility that connects nearby customers with your business.'],['growth','Authority Building','Ethical outreach and digital PR that strengthen credibility.'],['analytics','SEO Reporting','Transparent rankings, traffic, conversion, and opportunity reporting.']],
    processTitle: 'Lasting rankings begin with evidence and priorities.', workTitle: 'Websites positioned for discovery and growth.', work: ['/web/kbre.png','/web/mhlbadar.png','/web/azinterior.png'], cta: 'Ready to earn visibility from the searches that matter?',
  },
  uiux: {
    eyebrow: 'UI/UX Design Services', title: 'Digital experiences people', accent: 'understand and enjoy.',
    intro: 'We combine user research, product thinking, and visual design to create interfaces that feel intuitive, reduce friction, and guide users toward action.', hero: 'https://images.unsplash.com/photo-1586717791821-3f44a563fa4c?w=1200&q=85', heroAlt: 'UI UX interface design', feature: 'Clear interfaces shaped around real users', sectionTitle: 'Thoughtful product design from insight to interface.',
    services: [['search','User Research','Personas, journeys, interviews, and evidence that reveal real needs.'],['layers','UX Architecture','Clear flows, structures, and wireframes that simplify complex tasks.'],['palette','Interface Design','Polished, accessible interfaces aligned with your product and brand.'],['responsive','Responsive Design','Consistent experiences across mobile, tablet, and desktop.'],['boxes','Design Systems','Reusable components that improve consistency and delivery speed.'],['target','Usability Testing','Prototype validation before costly development decisions.']],
    processTitle: 'Great experiences are designed around evidence, not assumptions.', workTitle: 'Interfaces that balance beauty and usability.', work: ['/web/alzahracurtain.png','/web/nayizameen.png','/web/greenwood.png'], cta: 'Ready to make your digital product easier to love?',
  },
  'e-commerce': {
    eyebrow: 'E-commerce & Shopify Services', title: 'Online stores designed to', accent: 'sell more with less friction.',
    intro: 'We create high-performing Shopify and custom commerce experiences that make products easier to discover, compare, purchase, and return to.', hero: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=1200&q=85', heroAlt: 'Customer shopping online', feature: 'Commerce experiences optimized for conversion', sectionTitle: 'Everything needed to launch and scale your store.',
    services: [['shop','Shopify Development','Branded, flexible Shopify stores that are easy to manage.'],['code','Custom E-commerce','Tailored solutions for unique catalogs and workflows.'],['palette','Storefront UX','Conversion-focused collection, product, cart, and checkout journeys.'],['boxes','System Integrations','Payments, inventory, shipping, CRM, and marketplace connections.'],['gauge','Performance','Speed improvements that protect conversion and search visibility.'],['growth','Growth Optimization','Data-led improvements to merchandising and retention.']],
    processTitle: 'Successful commerce connects customer needs with operations.', workTitle: 'Storefronts built for confident buying.', work: ['/web/nayizameen.png','/web/alzahracurtain.png','/web/nooralaweer.png'], cta: 'Ready to build an online store customers return to?',
  },
  'video-editing': {
    eyebrow: 'Video Editing Services', title: 'Raw footage transformed into', accent: 'stories people remember.',
    intro: 'We shape footage into focused content with pacing, sound, color, motion, and platform-ready formats that hold attention from the first frame.', hero: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=1200&q=85', heroAlt: 'Professional video editing workstation', feature: 'Precision editing for every screen', sectionTitle: 'Post-production that gives every frame a purpose.',
    services: [['film','Professional Editing','Narrative structure, pacing, transitions, and final polish.'],['sparkles','Motion Graphics','Titles, explainers, lower thirds, and animated elements.'],['palette','Color Grading','Consistent cinematic color that establishes mood.'],['layers','Sound Design','Clean dialogue, balanced audio, music, and effects.'],['marketing','Social Video','Platform-native reels, ads, shorts, and captions.'],['boxes','Content Repurposing','Focused cutdowns and variations that extend every shoot.']],
    processTitle: 'A strong edit is where footage becomes communication.', workTitle: 'Every cut designed to keep attention.', work: ['/posters/3.jpeg','/posters/9.jpeg','/posters/16.jpeg'], caseStudy: '/case-studies/videography', cta: 'Ready to turn your footage into content that connects?',
  },
  videography: {
    eyebrow: 'Videography Services', title: 'Visual stories captured with', accent: 'purpose and cinematic craft.',
    intro: 'From concept and direction to filming and delivery, we produce professional video that gives brands, products, and events a compelling presence.', hero: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=1200&q=85', heroAlt: 'Professional cinema camera', feature: 'Production built around your story', sectionTitle: 'Complete video production for brands and campaigns.',
    services: [['camera','Brand Films','Story-led films that communicate who you are and why it matters.'],['film','Corporate Video','Interviews, profiles, training, and company communications.'],['marketing','Commercial Content','Product and campaign films for paid and organic channels.'],['sparkles','Event Coverage','Key moments and atmosphere captured with a polished style.'],['target','Creative Direction','Concepts, scripts, storyboards, planning, and on-set direction.'],['layers','Post-production','Editing, color, sound, graphics, captions, and final formats.']],
    processTitle: 'The best shoots are won in planning and elevated in post.', workTitle: 'Stories framed to create a lasting impression.', work: ['/posters/2.jpeg','/posters/11.jpeg','/posters/18.jpeg'], caseStudy: '/case-studies/videography', cta: 'Ready to bring your next story to the screen?',
  },
} satisfies Record<string, Config>

const process = [['Discover','We align on your goals, audience, competition, and priority outcomes.'],['Plan','We translate insight into a focused roadmap, deliverables, and milestones.'],['Create','Our specialists build, review, and refine with quality checks at every stage.'],['Deliver','You receive a polished solution, clear handover, and ongoing support.']]

export type ServicePageKey = keyof typeof configs

export default function ServiceDetailPage({ service }: { service: ServicePageKey }) {
  const c: Config = configs[service]
  return <main className="overflow-hidden bg-white text-[#191922]">
    <section className="relative isolate bg-[#f8f5f3] px-5 py-20 sm:px-8 lg:py-28"><div className="absolute -right-24 -top-20 -z-10 h-80 w-80 rounded-full bg-[#bf2227]/10 blur-3xl"/><div className="mx-auto grid max-w-7xl items-center gap-14 lg:grid-cols-[1.05fr_.95fr]">
      <div><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-[#bf2227]/20 bg-white px-4 py-2 text-xs font-bold uppercase tracking-[.18em] text-[#bf2227]"><Sparkles size={15}/>{c.eyebrow}</div><h1 className={`max-w-3xl font-montserrat text-4xl font-black tracking-tight sm:text-5xl lg:text-6xl ${service === 'graphic-desiging' ? 'leading-[1.18]' : 'leading-[1.08]'}`}>{c.title} <span className="text-[#bf2227]">{c.accent}</span></h1><p className="mt-6 max-w-2xl text-base leading-8 text-gray-600 sm:text-lg">{c.intro}</p><div className="mt-9 flex flex-wrap gap-4"><Link href="/contact-us" className="inline-flex items-center gap-2 rounded-full bg-[#bf2227] px-7 py-3.5 text-sm font-bold text-white shadow-lg shadow-red-900/15 transition hover:-translate-y-0.5">Start a project <ArrowRight size={17}/></Link>{c.caseStudy&&<Link href={c.caseStudy} className="rounded-full border border-gray-300 bg-white px-7 py-3.5 text-sm font-bold hover:border-[#bf2227] hover:text-[#bf2227]">View our work</Link>}</div><div className="mt-9 flex flex-wrap gap-x-7 gap-y-3 text-sm font-semibold text-gray-600">{['Strategy-led approach','Clear collaboration','Quality-assured delivery'].map(x=><span key={x} className="flex items-center gap-2"><BadgeCheck size={18} className="text-[#bf2227]"/>{x}</span>)}</div></div>
      <div className="relative mx-auto w-full max-w-xl"><div className="absolute -left-5 -top-5 h-full w-full rounded-[2rem] border-2 border-[#bf2227]/20"/><div className="relative aspect-[4/3] overflow-hidden rounded-[2rem] bg-[#201f27] shadow-2xl"><Image src={c.hero} alt={c.heroAlt} fill priority sizes="(max-width:1024px) 100vw,45vw" className="object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-black/70 via-transparent to-transparent"/><p className="absolute bottom-0 left-0 p-7 text-xl font-bold text-white">{c.feature}</p></div></div>
    </div></section>
    <section className="px-5 py-20 sm:px-8 lg:py-24"><div className="mx-auto max-w-7xl"><p className="text-sm font-bold uppercase tracking-[.2em] text-[#bf2227]">What we do</p><h2 className="mt-3 max-w-3xl font-montserrat text-3xl font-black sm:text-4xl">{c.sectionTitle}</h2><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{c.services.map(([icon,title,description])=>{const Icon=icons[icon];return <article key={title} className="group rounded-2xl border border-gray-200 p-7 transition hover:-translate-y-1 hover:border-[#bf2227]/35 hover:shadow-xl"><div className="flex h-12 w-12 items-center justify-center rounded-xl bg-red-50 text-[#bf2227] group-hover:bg-[#bf2227] group-hover:text-white"><Icon size={23}/></div><h3 className="mt-6 text-lg font-extrabold">{title}</h3><p className="mt-3 text-sm leading-7 text-gray-600">{description}</p></article>})}</div></div></section>
    <section className="bg-[#1d1c24] px-5 py-20 text-white sm:px-8 lg:py-24"><div className="mx-auto grid max-w-7xl gap-14 lg:grid-cols-[.8fr_1.2fr]"><div><div className="flex h-12 w-12 items-center justify-center rounded-xl bg-[#bf2227]"><Brush size={23}/></div><p className="mt-7 text-sm font-bold uppercase tracking-[.2em] text-red-300">Our process</p><h2 className="mt-3 font-montserrat text-3xl font-black sm:text-4xl">{c.processTitle}</h2></div><div className="grid gap-px overflow-hidden rounded-2xl bg-white/10 sm:grid-cols-2">{process.map(([title,description],i)=><div key={title} className="bg-[#25242d] p-8"><span className="text-sm font-black text-[#e95459]">0{i+1}</span><h3 className="mt-4 text-xl font-extrabold">{title}</h3><p className="mt-3 text-sm leading-7 text-white/60">{description}</p></div>)}</div></div></section>
    <section className="px-5 py-20 sm:px-8 lg:py-24"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-sm font-bold uppercase tracking-[.2em] text-[#bf2227]">Selected work</p><h2 className="mt-3 font-montserrat text-3xl font-black sm:text-4xl">{c.workTitle}</h2></div>{c.caseStudy&&<Link href={c.caseStudy} className="inline-flex items-center gap-2 text-sm font-bold text-[#bf2227]">Explore case studies <ArrowRight size={17}/></Link>}</div><div className="mt-10 grid gap-5 md:grid-cols-3">{c.work.map((src,i)=><div key={src} className={`overflow-hidden rounded-2xl bg-gray-100 ${i===1?'md:-translate-y-3':''}`}><div className="relative aspect-square"><Image src={src} alt={`${c.eyebrow} portfolio project`} fill sizes="(max-width:768px) 100vw,33vw" className="object-cover transition duration-500 hover:scale-105"/></div></div>)}</div></div></section>
    <section className="px-5 pb-20 sm:px-8 lg:pb-28"><div className="mx-auto max-w-7xl overflow-hidden rounded-[2rem] bg-[#bf2227] px-6 py-12 text-white sm:px-12 lg:flex lg:items-center lg:justify-between lg:px-16 lg:py-16"><div className="max-w-2xl"><p className="text-sm font-bold uppercase tracking-[.2em] text-white/70">Let&apos;s build what&apos;s next</p><h2 className="mt-3 font-montserrat text-3xl font-black sm:text-4xl">{c.cta}</h2><div className="mt-6 flex flex-wrap gap-5 text-sm text-white/85">{['Clear scope','Dedicated team','Reliable communication'].map(x=><span key={x} className="flex items-center gap-2"><Check size={17}/>{x}</span>)}</div></div><Link href="/contact-us" className="mt-8 inline-flex shrink-0 items-center gap-2 rounded-full bg-white px-7 py-3.5 text-sm font-extrabold text-[#bf2227] lg:ml-10 lg:mt-0">Get a free consultation <ArrowRight size={17}/></Link></div></section>
  </main>
}
